import {createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
export const PERMISSIONS=['payments:read','payments.links:manage','payments.refunds:request','payments.refunds:approve','settlements:read','settlements:manage','settlements:approve','reconciliation:read','reconciliation:manage','reconciliation:approve','ledger:read','ledger:integrity','reports:read','reports:export','audit:read','developer.apiKeys:manage','developer.webhooks:manage','team:read','team:manage','roles:read','roles:manage','sessions:read','sessions:manage','security:manage:self','onboarding:read','onboarding:write','onboarding:submit','compliance:read','compliance:review','compliance:approve'] as const;
export const SYSTEM_ROLES=['Owner','Administrator','Finance','Developer','Support','Viewer'] as const;
export const normalizeEmail=(value:string)=>value.trim().toLowerCase();
export function validatePermissions(values:string[],granter:string[],owner=false){const unique=[...new Set(values)];if(unique.some(v=>!PERMISSIONS.includes(v as any)))throw new Error('UNKNOWN_PERMISSION');if(!owner&&unique.some(v=>!granter.includes(v)))throw new Error('PERMISSION_ESCALATION');return unique.sort();}
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
const encodeBase32=(input:Buffer)=>{let bits=0,value=0,result='';for(const byte of input){value=(value<<8)|byte;bits+=8;while(bits>=5){result+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits)result+=alphabet[(value<<(5-bits))&31];return result;};
const decodeBase32=(input:string)=>{let bits=0,value=0;const bytes:number[]=[];for(const char of input.toUpperCase().replace(/=+$/,'')){const index=alphabet.indexOf(char);if(index<0)throw new Error('INVALID_TOTP_SECRET');value=(value<<5)|index;bits+=5;if(bits>=8){bytes.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(bytes);};
export function generateTotpSecret(){return encodeBase32(randomBytes(20));}
export function totp(secret:string,time=Date.now(),step=30){const counter=Math.floor(time/1000/step),buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const digest=createHmac('sha1',decodeBase32(secret)).update(buffer).digest(),offset=digest[digest.length-1]!&15,number=((digest[offset]!&127)<<24)|(digest[offset+1]!<<16)|(digest[offset+2]!<<8)|digest[offset+3]!;return {code:String(number%1_000_000).padStart(6,'0'),counter};}
export function verifyTotp(secret:string,code:string,lastCounter:number|null,time=Date.now()){for(let skew=-1;skew<=1;skew++){const candidate=totp(secret,time+skew*30_000);if(candidate.counter>(lastCounter??-1)&&code.length===candidate.code.length&&timingSafeEqual(Buffer.from(code),Buffer.from(candidate.code)))return candidate.counter;}return null;}
export function recoveryCodes(count=10){return Array.from({length:count},()=>randomBytes(9).toString('base64url'));}
