import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Config } from '../config.js';
import type { Db } from '../db.js';
import { transaction } from '../db.js';
import type { RateLimitStore } from '../rateLimit.js';
import { apiError,authenticateSessionOrApiKey,newId,requirePermission,requireSession } from '../security.js';
import { canonical,MAX_REPORT_ROWS,ReportError,reportCsv,safeAuditMetadata,sha256,validateReportRequest,type ReportType } from './reporting.js';

const requestSchema=z.object({reportType:z.string(),currency:z.string(),periodStart:z.string(),periodEnd:z.string()});
const page=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)});
const columns:Record<ReportType,string[]>={
  TRANSACTION_ACTIVITY:['id','reference','status','channel','gross_minor','fee_minor','refunded_minor','currency','created_at'],
  REFUND_ACTIVITY:['id','reference','payment_id','status','amount_minor','currency','created_at'],
  PLATFORM_FEES:['payment_id','reference','fee_minor','currency','updated_at'],
  MERCHANT_LEDGER:['entry_id','source_type','source_id','description','direction','amount_minor','currency','posted_at'],
  RECONCILIATION_RESULTS:['id','status','source_count','matched_count','unmatched_count','currency','period_start','period_end','completed_at'],
  SANDBOX_SETTLEMENT_SUMMARIES:['id','status','gross_minor','refunds_minor','fees_minor','net_minor','currency','period_start','period_end','external_transfer_executed'],
};
async function sourceRows(c:any,merchant:string,q:ReturnType<typeof validateReportRequest>){
  const args=[merchant,q.currency,q.periodStart,q.periodEnd,MAX_REPORT_ROWS+1];
  const sql:Record<ReportType,string>={
    TRANSACTION_ACTIVITY:`SELECT id,reference,status,channel,gross_minor::text,fee_minor::text,refunded_minor::text,currency,created_at FROM payments WHERE merchant_id=$1 AND currency=$2 AND created_at>=$3 AND created_at<$4 ORDER BY created_at,id LIMIT $5`,
    REFUND_ACTIVITY:`SELECT r.id,r.reference,r.payment_id,r.status,r.amount_minor::text,p.currency,r.created_at FROM refunds r JOIN payments p ON p.id=r.payment_id AND p.merchant_id=r.merchant_id WHERE r.merchant_id=$1 AND p.currency=$2 AND r.created_at>=$3 AND r.created_at<$4 ORDER BY r.created_at,r.id LIMIT $5`,
    PLATFORM_FEES:`SELECT id payment_id,reference,fee_minor::text,currency,updated_at FROM payments WHERE merchant_id=$1 AND currency=$2 AND updated_at>=$3 AND updated_at<$4 ORDER BY updated_at,id LIMIT $5`,
    MERCHANT_LEDGER:`SELECT j.id entry_id,j.source_type,j.source_id,j.description,p.direction,p.amount_minor::text,p.currency,j.posted_at FROM journal_entries j JOIN journal_postings p ON p.entry_id=j.id JOIN ledger_accounts a ON a.id=p.account_id AND a.owner_type='MERCHANT' AND a.merchant_id=j.merchant_id WHERE j.merchant_id=$1 AND p.currency=$2 AND j.posted_at>=$3 AND j.posted_at<$4 ORDER BY j.posted_at,j.id,p.id LIMIT $5`,
    RECONCILIATION_RESULTS:`SELECT id,status,source_count,matched_count,unmatched_count,currency,period_start,period_end,completed_at FROM reconciliation_runs WHERE merchant_id=$1 AND currency=$2 AND started_at>=$3 AND started_at<$4 ORDER BY started_at,id LIMIT $5`,
    SANDBOX_SETTLEMENT_SUMMARIES:`SELECT id,status,gross_minor::text,refunds_minor::text,fees_minor::text,net_minor::text,currency,period_start,period_end,external_transfer_executed FROM settlement_batches WHERE merchant_id=$1 AND currency=$2 AND created_at>=$3 AND created_at<$4 ORDER BY created_at,id LIMIT $5`,
  };
  const rows=(await c.query(sql[q.reportType],args)).rows;
  if(rows.length>MAX_REPORT_ROWS)throw new ReportError('REPORT_ROW_LIMIT_EXCEEDED',`Reports cannot exceed ${MAX_REPORT_ROWS} rows.`);
  return rows.map((row:any)=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,v instanceof Date?v.toISOString():v])));
}
const handle=(r:FastifyRequest,p:FastifyReply,error:unknown)=>{if(error instanceof ReportError)return p.code(error.statusCode).send(apiError(r,error.code,error.message));throw error;};
export async function registerReportingRoutes(app:FastifyInstance,config:Config,db:Db,limits:RateLimitStore){
  const auth=authenticateSessionOrApiKey(db,config.PASSWORD_PEPPER,limits,config),sessionOnly=async(r:FastifyRequest,p:FastifyReply)=>{requireSession(r,p);},read=[auth,requirePermission('reports:read')],exports=[auth,sessionOnly,requirePermission('reports:export')],audit=[auth,sessionOnly,requirePermission('audit:read')];
  app.get('/v1/reports/summary',{preHandler:read},async(r,p)=>{try{const q=validateReportRequest(requestSchema.parse(r.query));const x=(await db.query(`SELECT coalesce(sum(gross_minor) FILTER(WHERE status IN ('SUCCEEDED','PARTIALLY_REFUNDED','REFUNDED')),0)::text gross_payment_minor,count(*) FILTER(WHERE status IN ('SUCCEEDED','PARTIALLY_REFUNDED','REFUNDED'))::int successful_payment_count,count(*) FILTER(WHERE status IN ('FAILED','EXPIRED'))::int failed_payment_count,coalesce(sum(refunded_minor),0)::text refunded_minor,coalesce(sum(fee_minor),0)::text fee_minor FROM payments WHERE merchant_id=$1 AND currency=$2 AND created_at>=$3 AND created_at<$4`,[r.actor!.merchantId,q.currency,q.periodStart,q.periodEnd])).rows[0];const ledger=(await db.query(`SELECT coalesce(sum(p.amount_minor) FILTER(WHERE p.direction='DEBIT'),0)::text debit_minor,coalesce(sum(p.amount_minor) FILTER(WHERE p.direction='CREDIT'),0)::text credit_minor FROM journal_entries j JOIN journal_postings p ON p.entry_id=j.id WHERE j.merchant_id=$1 AND p.currency=$2 AND j.posted_at>=$3 AND j.posted_at<$4`,[r.actor!.merchantId,q.currency,q.periodStart,q.periodEnd])).rows[0];const rec=(await db.query(`SELECT coalesce(sum(matched_count),0)::int matched_count,coalesce(sum(unmatched_count),0)::int exception_count FROM reconciliation_runs WHERE merchant_id=$1 AND currency=$2 AND started_at>=$3 AND started_at<$4`,[r.actor!.merchantId,q.currency,q.periodStart,q.periodEnd])).rows[0];const set=(await db.query(`SELECT coalesce(sum(net_minor),0)::text net_minor,count(*)::int count FROM settlement_batches WHERE merchant_id=$1 AND currency=$2 AND created_at>=$3 AND created_at<$4`,[r.actor!.merchantId,q.currency,q.periodStart,q.periodEnd])).rows[0];return {merchantId:r.actor!.merchantId,currency:q.currency,periodStart:q.periodStart,periodEnd:q.periodEnd,reportType:q.reportType,environment:'sandbox',generatedAt:new Date().toISOString(),grossPaymentMinor:x.gross_payment_minor,successfulPaymentCount:x.successful_payment_count,failedPaymentCount:x.failed_payment_count,refundedMinor:x.refunded_minor,feeMinor:x.fee_minor,netMerchantMinor:(BigInt(x.gross_payment_minor)-BigInt(x.refunded_minor)-BigInt(x.fee_minor)).toString(),ledgerDebitMinor:ledger.debit_minor,ledgerCreditMinor:ledger.credit_minor,reconciliationMatchedCount:rec.matched_count,reconciliationExceptionCount:rec.exception_count,sandboxSettlementNetMinor:set.net_minor,sandboxSettlementCount:set.count};}catch(e){return handle(r,p,e);}});
  app.post('/v1/report-exports',{preHandler:exports},async(r,p)=>{try{const q=validateReportRequest(requestSchema.parse(r.body)),key=z.string().min(8).max(128).parse(r.headers['idempotency-key']),requestHash=sha256(canonical(q));const result=await transaction(db,async c=>{await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${r.actor!.merchantId}:report:${key}`]);const prior=await c.query('SELECT * FROM report_exports WHERE merchant_id=$1 AND idempotency_key=$2',[r.actor!.merchantId,key]);if(prior.rowCount){if(prior.rows[0].request_sha256!==requestHash)throw new ReportError('REPORT_IDEMPOTENCY_CONFLICT','The idempotency key was reused with different parameters.',409);return prior.rows[0];}const rows=await sourceRows(c,r.actor!.merchantId!,q),snapshot={reportType:q.reportType,currency:q.currency,periodStart:q.periodStart,periodEnd:q.periodEnd,rowCount:rows.length,rows},sourceHash=sha256(canonical(snapshot)),csv=reportCsv(columns[q.reportType],rows),id=newId('rpt'),contentHash=sha256(csv);const created=(await c.query(`INSERT INTO report_exports(id,merchant_id,report_type,currency,period_start,period_end,status,requested_by,idempotency_key,request_sha256,source_snapshot,source_sha256,content_sha256,csv_content,row_count,completed_at) VALUES($1,$2,$3,$4,$5,$6,'COMPLETED',$7,$8,$9,$10,$11,$12,$13,$14,now()) RETURNING *`,[id,r.actor!.merchantId,q.reportType,q.currency,q.periodStart,q.periodEnd,r.actor!.id,key,requestHash,snapshot,sourceHash,contentHash,csv,rows.length])).rows[0];await c.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id) VALUES($1,$2,$3,'REPORT_EXPORT_REQUESTED','report_export',$4),($5,$2,$3,'REPORT_EXPORT_COMPLETED','report_export',$4)`,[newId('aud'),r.actor!.id,r.actor!.merchantId,id,newId('aud')]);return created;});p.code(201);return viewExport(result);}catch(e){return handle(r,p,e);}});
  app.get('/v1/report-exports',{preHandler:read},async r=>{const q=page.parse(r.query),x=await db.query('SELECT *,count(*) OVER() total FROM report_exports WHERE merchant_id=$1 ORDER BY created_at DESC,id DESC LIMIT $2 OFFSET $3',[r.actor!.merchantId,q.pageSize,(q.page-1)*q.pageSize]);return {data:x.rows.map(viewExport),page:q.page,pageSize:q.pageSize,total:Number(x.rows[0]?.total??0)};});
  app.get('/v1/report-exports/:id',{preHandler:read},async(r,p)=>{const x=await db.query('SELECT * FROM report_exports WHERE id=$1 AND merchant_id=$2',[(r.params as any).id,r.actor!.merchantId]);return x.rowCount?viewExport(x.rows[0]):p.code(404).send(apiError(r,'REPORT_EXPORT_NOT_FOUND','Report export not found.'));});
  app.get('/v1/report-exports/:id/download',{preHandler:read},async(r,p)=>{const x=await db.query(`SELECT * FROM report_exports WHERE id=$1 AND merchant_id=$2`,[(r.params as any).id,r.actor!.merchantId]);if(!x.rowCount)return p.code(404).send(apiError(r,'REPORT_EXPORT_NOT_FOUND','Report export not found.'));if(x.rows[0].status!=='COMPLETED'||!x.rows[0].csv_content)return p.code(409).send(apiError(r,'REPORT_EXPORT_NOT_READY','Report export is not ready.'));await db.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id) VALUES($1,$2,$3,'REPORT_DOWNLOADED','report_export',$4)`,[newId('aud'),r.actor!.id,r.actor!.merchantId,x.rows[0].id]);const filename=`${String(x.rows[0].report_type).toLowerCase()}-${x.rows[0].id}.csv`;p.header('Content-Type','text/csv; charset=utf-8').header('Content-Disposition',`attachment; filename="${filename}"`).header('X-Content-Type-Options','nosniff');return x.rows[0].csv_content;});
  app.get('/v1/audit-events',{preHandler:audit},async r=>{const q=page.extend({action:z.string().max(100).optional(),resourceType:z.string().max(100).optional(),actorId:z.string().max(200).optional(),periodStart:z.iso.datetime().optional(),periodEnd:z.iso.datetime().optional()}).parse(r.query),x=await db.query(`SELECT *,count(*) OVER() total FROM audit_events WHERE merchant_id=$1 AND ($2::text IS NULL OR action=$2) AND ($3::text IS NULL OR resource_type=$3) AND ($4::text IS NULL OR actor_id=$4) AND ($5::timestamptz IS NULL OR occurred_at>=$5) AND ($6::timestamptz IS NULL OR occurred_at<$6) ORDER BY occurred_at DESC,id DESC LIMIT $7 OFFSET $8`,[r.actor!.merchantId,q.action??null,q.resourceType??null,q.actorId??null,q.periodStart??null,q.periodEnd??null,q.pageSize,(q.page-1)*q.pageSize]);return {data:x.rows.map((v:any)=>({id:v.id,actorId:v.actor_id,action:v.action,resourceType:v.resource_type,resourceId:v.resource_id,metadata:safeAuditMetadata(v.metadata),occurredAt:v.occurred_at})),page:q.page,pageSize:q.pageSize,total:Number(x.rows[0]?.total??0)};});
}
function viewExport(v:any){return {id:v.id,reportType:v.report_type,currency:v.currency,periodStart:v.period_start,periodEnd:v.period_end,status:v.status,rowCount:v.row_count,sourceSha256:v.source_sha256,contentSha256:v.content_sha256,sandboxOnly:v.sandbox_only,createdAt:v.created_at,completedAt:v.completed_at,failureCode:v.failure_code};}
