import {lazy} from 'react';
export const LoginPage=lazy(()=>import('@/pages/StaffLoginPage'));
export const NotFoundPage=lazy(()=>import('@/pages/NotFoundPage'));
export const AdminSupportPage=lazy(()=>import('@/pages/admin/AdminSupportPage'));
export const AdminSupportDetailPage=lazy(()=>import('@/pages/admin/AdminSupportDetailPage'));
export const AdminHomePage=lazy(()=>import('@/pages/AdminHomePage'));
export const MerchantApplicationsListPage=lazy(()=>import('@/pages/MerchantApplicationsListPage'));
export const MerchantApplicationDetailPage=lazy(()=>import('@/pages/MerchantApplicationDetailPage'));
export const PendingRefundApprovalsPage=lazy(()=>import('@/pages/PendingRefundApprovalsPage'));
export const AuditLogsPage=lazy(()=>import('@/pages/AuditLogsPage'));
export const SystemHealthPage=lazy(()=>import('@/pages/SystemHealthPage'));
const platform=()=>import('@/pages/admin/PlatformResourcePages');
export const AdminMerchantsPage=lazy(()=>platform().then(m=>({default:m.AdminMerchantsPage})));
export const AdminMerchantDetailPage=lazy(()=>platform().then(m=>({default:m.AdminMerchantDetailPage})));
export const AdminTransactionsPage=lazy(()=>platform().then(m=>({default:m.AdminTransactionsPage})));
export const AdminTransactionDetailPage=lazy(()=>platform().then(m=>({default:m.AdminTransactionDetailPage})));
export const AdminRefundsPage=lazy(()=>platform().then(m=>({default:m.AdminRefundsPage})));
export const AdminSettlementsPage=lazy(()=>platform().then(m=>({default:m.AdminSettlementsPage})));
export const AdminReconciliationPage=lazy(()=>platform().then(m=>({default:m.AdminReconciliationPage})));
export const AdminExceptionsPage=lazy(()=>platform().then(m=>({default:m.AdminExceptionsPage})));
export const AdminExceptionDetailPage=lazy(()=>platform().then(m=>({default:m.AdminExceptionDetailPage})));
export const AdminProvidersPage=lazy(()=>platform().then(m=>({default:m.AdminProvidersPage})));
export const AdminUsersPage=lazy(()=>platform().then(m=>({default:m.AdminUsersPage})));
export const AdminRolesPage=lazy(()=>platform().then(m=>({default:m.AdminRolesPage})));
export const AdminIncidentsPage=lazy(()=>platform().then(m=>({default:m.AdminIncidentsPage})));
export const AdminSecurityPage=lazy(()=>platform().then(m=>({default:m.AdminSecurityPage})));
export const AdminReportsPage=lazy(()=>platform().then(m=>({default:m.AdminReportsPage})));
export const AdminSettingsPage=lazy(()=>platform().then(m=>({default:m.AdminSettingsPage})));
