import { createHash } from 'node:crypto';
import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Config } from '../config.js';
import type { Db } from '../db.js';
import { transaction } from '../db.js';
import { rateLimit,type RateLimitStore } from '../rateLimit.js';
import { apiError,authenticate,newId } from '../security.js';
import { operationalMetrics } from './metrics.js';

const states=['DECLARED','INVESTIGATING','IDENTIFIED','MONITORING','RESOLVED','CLOSED'] as const,severities=['SEV1','SEV2','SEV3','SEV4'] as const,scopes=['PLATFORM','MERCHANTS','PAYMENTS','REFUNDS','SETTLEMENTS','RECONCILIATION','WEBHOOKS','NOTIFICATIONS','AUTHENTICATION','DATABASE','CACHE','OTHER'] as const,controls=['PAYMENT_CREATION_PAUSED','REFUND_MUTATIONS_PAUSED','SETTLEMENT_PROCESSING_PAUSED','WEBHOOK_DELIVERY_PAUSED','NOTIFICATION_PROCESSING_PAUSED','OUTBOX_PROCESSING_PAUSED','DISPUTE_MUTATIONS_PAUSED','ONBOARDING_SUBMISSIONS_PAUSED'] as const;
const identifier=z.string().min(1).max(200),key=z.string().min(8).max(128),reason=z.string().trim().min(3).max(1000);
const canonical=(x:any):string=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?`[${x.map(canonical).join(',')}]`:`{${Object.keys(x).sort().map(k=>`${JSON.stringify(k)}:${canonical(x[k])}`).join(',')}}`,sha=(x:unknown)=>createHash('sha256').update(canonical(x)).digest('hex');
class OperationsError extends Error{constructor(public code:string,message:string,public status=409){super(message)}}
const fail=(r:FastifyRequest,p:FastifyReply,e:unknown)=>e instanceof OperationsError?p.code(e.status).send(apiError(r,e.code,e.message)):(e as any)?.code==='23514'?p.code(409).send(apiError(r,'OPERATIONAL_STATE_CONFLICT','The requested operational state transition is not allowed.')):Promise.reject(e);
const guard=(db:Db,config:Config,permission:string)=>async(r:FastifyRequest,p:FastifyReply)=>{if(r.headers.authorization)return p.code(403).send(apiError(r,'FORBIDDEN','A browser session is required.'));await authenticate(db,config,r,p);if(p.sent)return;if(r.actor?.merchantId!==null||r.actor?.role!=='PLATFORM_ADMIN')return p.code(403).send(apiError(r,'PLATFORM_PERMISSION_DENIED','Platform staff authority is required.'));if(!r.actor.permissions.includes(permission))return p.code(403).send(apiError(r,'PLATFORM_PERMISSION_DENIED','The required operational permission is missing.'));};
async function idem(c:any,r:FastifyRequest,operation:string,resource:string,input:unknown,work:()=>Promise<{status:number,body:any}>){const k=key.parse(r.headers['idempotency-key']),hash=sha(input);await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`operations:${r.actor!.id}:${operation}:${resource}:${k}`]);const old=(await c.query('SELECT * FROM operational_idempotency WHERE authority_scope=$1 AND actor_id=$2 AND operation=$3 AND resource_id=$4 AND idempotency_key=$5',['PLATFORM',r.actor!.id,operation,resource,k])).rows[0];if(old){if(old.request_sha256!==hash){operationalMetrics.increment('idempotency_requests_total',{operation:'operations',outcome:'conflict'});throw new OperationsError('IDEMPOTENCY_CONFLICT','The idempotency key was reused with different input.');}operationalMetrics.increment('idempotency_requests_total',{operation:'operations',outcome:'replay'});return {status:old.response_status,body:old.response_body};}const out=await work();await c.query('INSERT INTO operational_idempotency(authority_scope,actor_id,operation,resource_id,idempotency_key,request_sha256,response_status,response_body) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',['PLATFORM',r.actor!.id,operation,resource,k,hash,out.status,out.body]);operationalMetrics.increment('idempotency_requests_total',{operation:'operations',outcome:'stored'});return out;}
async function evidence(c:any,r:FastifyRequest,action:string,type:string,id:string,metadata:object={}){await c.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id,metadata) VALUES($1,$2,NULL,$3,$4,$5,$6)`,[newId('aud'),r.actor!.id,action,type,id,metadata]);await c.query(`INSERT INTO outbox_events(id,event_type,aggregate_type,aggregate_id,payload,deduplication_key) VALUES($1,$2,$3,$4,$5,$6)`,[newId('obx'),action.toLowerCase().replaceAll('_','.'),type,id,{resourceId:id,...metadata},`${action}:${id}:${newId('evt')}`]);}
const incident=(x:any)=>({id:x.id,reference:x.reference,title:x.title,summary:x.summary,severity:x.severity,state:x.state,impactScope:x.impact_scope,incidentCommander:x.incident_commander,version:Number(x.version),createdAt:x.created_at,updatedAt:x.updated_at,resolvedAt:x.resolved_at,closedAt:x.closed_at});
export async function isOperationalControlActive(db:Pick<Db,'query'>,controlKey:string){const row=(await db.query(`SELECT h.active,h.expires_at FROM operational_control_history h JOIN operational_control_requests r ON r.id=h.request_id AND r.status='APPROVED' JOIN operational_control_decisions d ON d.request_id=r.id AND d.decision='APPROVED' WHERE h.control_key=$1 ORDER BY h.created_at DESC,h.id DESC LIMIT 1`,[controlKey])).rows[0];return Boolean(row?.active&&(!row.expires_at||new Date(row.expires_at)>new Date()));}

export async function registerOperationsRoutes(app:FastifyInstance,config:Config,db:Db,limits:RateLimitStore){
 const read=guard(db,config,'platform.incidents.read'),manage=guard(db,config,'platform.incidents.manage'),controlRead=guard(db,config,'platform.controls.read'),propose=guard(db,config,'platform.controls.propose'),approve=guard(db,config,'platform.controls.approve');
 const mutationLimit=rateLimit(limits,config,'operational-incident-mutation',30,60,r=>`platform:${r.actor?.id}`),overviewLimit=rateLimit(limits,config,'operational-overview',60,60,r=>`platform:${r.actor?.id}`);
 app.get('/v1/platform/operations/incidents',{preHandler:read},async r=>{const q=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25)}).parse(r.query),offset=(q.page-1)*q.pageSize,total=Number((await db.query('SELECT count(*) FROM operational_incidents')).rows[0].count),rows=(await db.query(`SELECT * FROM operational_incidents ORDER BY created_at DESC,id DESC LIMIT $1 OFFSET $2`,[q.pageSize,offset])).rows;return {data:rows.map(incident),page:q.page,pageSize:q.pageSize,total};});
 app.post('/v1/platform/operations/incidents',{preHandler:[manage,rateLimit(limits,config,'operational-incident-create',10,60,r=>`platform:${r.actor?.id}`)]},async(r,p)=>{try{const b=z.object({reference:z.string().trim().min(3).max(100),title:z.string().trim().min(3).max(160),summary:z.string().trim().min(3).max(2000),severity:z.enum(severities),impactScope:z.enum(scopes),reason}).parse(r.body),out=await transaction(db,async c=>idem(c,r,'incident.create','',b,async()=>{const id=newId('inc'),row=(await c.query(`INSERT INTO operational_incidents(id,reference,title,summary,severity,impact_scope,declared_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[id,b.reference,b.title,b.summary,b.severity,b.impactScope,r.actor!.id])).rows[0];await c.query(`INSERT INTO operational_incident_history(id,incident_id,actor_id,from_state,to_state,reason) VALUES($1,$2,$3,NULL,'DECLARED',$4)`,[newId('ihs'),id,r.actor!.id,b.reason]);await evidence(c,r,'OPERATIONAL_INCIDENT_DECLARED','operational_incident',id,{severity:b.severity,impactScope:b.impactScope,state:'DECLARED'});operationalMetrics.increment('operational_incidents_total',{state:'declared',severity:b.severity.toLowerCase()});return {status:201,body:incident(row)};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});
 app.get('/v1/platform/operations/incidents/:id',{preHandler:read},async(r,p)=>{const row=(await db.query('SELECT * FROM operational_incidents WHERE id=$1',[(r.params as any).id])).rows[0];return row?incident(row):p.code(404).send(apiError(r,'OPERATIONAL_INCIDENT_NOT_FOUND','Incident not found.'));});
 const mutate=async(r:FastifyRequest,p:FastifyReply,operation:string,body:any,work:(c:any,row:any)=>Promise<any>)=>{try{const iid=identifier.parse((r.params as any).id),out=await transaction(db,async c=>idem(c,r,operation,iid,{incidentId:iid,...body},async()=>{const row=(await c.query('SELECT * FROM operational_incidents WHERE id=$1 FOR UPDATE',[iid])).rows[0];if(!row)throw new OperationsError('OPERATIONAL_INCIDENT_NOT_FOUND','Incident not found.',404);if(row.version!==body.expectedVersion)throw new OperationsError('OPERATIONAL_INCIDENT_STALE','Incident version changed.');return {status:200,body:await work(c,row)};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}};
 app.post('/v1/platform/operations/incidents/:id/notes',{preHandler:[manage,mutationLimit]},async(r,p)=>{const b=z.object({body:z.string().trim().min(3).max(4000),reason,expectedVersion:z.number().int().positive()}).parse(r.body);return mutate(r,p,'incident.note',b,async(c,row)=>{const noteId=newId('ino');await c.query('INSERT INTO operational_incident_notes(id,incident_id,actor_id,body) VALUES($1,$2,$3,$4)',[noteId,row.id,r.actor!.id,b.body]);await c.query('UPDATE operational_incidents SET version=version+1,updated_at=now() WHERE id=$1',[row.id]);await evidence(c,r,'OPERATIONAL_INCIDENT_NOTE_ADDED','operational_incident',row.id,{noteId});return {id:noteId,incidentId:row.id,version:row.version+1};});});
 app.post('/v1/platform/operations/incidents/:id/assign',{preHandler:[manage,mutationLimit]},async(r,p)=>{const b=z.object({staffId:identifier,reason,expectedVersion:z.number().int().positive()}).parse(r.body);return mutate(r,p,'incident.assign',b,async(c,row)=>{if(!(await c.query(`SELECT 1 FROM users WHERE id=$1 AND merchant_id IS NULL AND role='PLATFORM_ADMIN' AND status='ACTIVE' AND permissions@>ARRAY['platform.incidents.read']`,[b.staffId])).rowCount)throw new OperationsError('OPERATIONAL_ASSIGNEE_INELIGIBLE','Incident commander is not eligible.',422);await c.query('UPDATE operational_incidents SET incident_commander=$1,version=version+1,updated_at=now() WHERE id=$2',[b.staffId,row.id]);await evidence(c,r,'OPERATIONAL_INCIDENT_ASSIGNED','operational_incident',row.id,{incidentCommander:b.staffId});return {...incident(row),incidentCommander:b.staffId,version:row.version+1};});});
 app.post('/v1/platform/operations/incidents/:id/status',{preHandler:[manage,mutationLimit]},async(r,p)=>{const b=z.object({status:z.enum(states),reason,expectedState:z.enum(states),expectedVersion:z.number().int().positive()}).parse(r.body);return mutate(r,p,'incident.status',b,async(c,row)=>{if(row.state!==b.expectedState)throw new OperationsError('OPERATIONAL_INCIDENT_STALE','Incident state changed.');await c.query(`UPDATE operational_incidents SET state=$1,version=version+1,updated_at=now(),resolved_at=CASE WHEN $1='RESOLVED' THEN now() WHEN $1='MONITORING' THEN NULL ELSE resolved_at END,closed_at=CASE WHEN $1='CLOSED' THEN now() ELSE closed_at END WHERE id=$2`,[b.status,row.id]);await c.query('INSERT INTO operational_incident_history(id,incident_id,actor_id,from_state,to_state,reason) VALUES($1,$2,$3,$4,$5,$6)',[newId('ihs'),row.id,r.actor!.id,row.state,b.status,b.reason]);await evidence(c,r,'OPERATIONAL_INCIDENT_STATUS_CHANGED','operational_incident',row.id,{fromState:row.state,toState:b.status});return {...incident(row),state:b.status,version:row.version+1};});});
 app.post('/v1/platform/operations/incidents/:id/severity',{preHandler:[manage,mutationLimit]},async(r,p)=>{const b=z.object({severity:z.enum(severities),reason,expectedSeverity:z.enum(severities),expectedVersion:z.number().int().positive()}).parse(r.body);return mutate(r,p,'incident.severity',b,async(c,row)=>{if(row.severity!==b.expectedSeverity)throw new OperationsError('OPERATIONAL_INCIDENT_STALE','Incident severity changed.');await c.query('UPDATE operational_incidents SET severity=$1,version=version+1,updated_at=now() WHERE id=$2',[b.severity,row.id]);await evidence(c,r,'OPERATIONAL_INCIDENT_SEVERITY_CHANGED','operational_incident',row.id,{fromSeverity:row.severity,toSeverity:b.severity});return {...incident(row),severity:b.severity,version:row.version+1};});});
 app.get('/v1/platform/operations/controls',{preHandler:controlRead},async()=>({data:await Promise.all(controls.map(async controlKey=>({controlKey,active:await isOperationalControlActive(db,controlKey)})))}));
 app.get('/v1/platform/operations/controls/:key',{preHandler:controlRead},async(r,p)=>{const controlKey=z.enum(controls).safeParse((r.params as any).key);if(!controlKey.success)return p.code(404).send(apiError(r,'OPERATIONAL_CONTROL_NOT_FOUND','Control not found.'));return {controlKey:controlKey.data,active:await isOperationalControlActive(db,controlKey.data)};});
 app.post('/v1/platform/operations/controls/:key/proposals',{preHandler:[propose,rateLimit(limits,config,'operational-control-proposal',10,60,r=>`platform:${r.actor?.id}`)]},async(r,p)=>{try{const controlKey=z.enum(controls).parse((r.params as any).key),b=z.object({requestedActive:z.boolean(),expectedActive:z.boolean(),reason,expiresAt:z.iso.datetime().optional()}).parse(r.body),out=await transaction(db,async c=>idem(c,r,'control.propose',controlKey,b,async()=>{if(await isOperationalControlActive(c,controlKey)!==b.expectedActive)throw new OperationsError('OPERATIONAL_CONTROL_STALE','Control state changed.');const id=newId('ocr');await c.query(`INSERT INTO operational_control_requests(id,control_key,requested_active,expected_active,reason,expires_at,proposed_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,controlKey,b.requestedActive,b.expectedActive,b.reason,b.expiresAt??null,r.actor!.id]);await evidence(c,r,'OPERATIONAL_CONTROL_PROPOSED','operational_control',id,{controlKey,requestedActive:b.requestedActive});return {status:201,body:{id,controlKey,status:'PROPOSED',requestedActive:b.requestedActive}};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});
 const decide=async(r:FastifyRequest,p:FastifyReply,decision:'APPROVED'|'REJECTED')=>{try{const proposalId=identifier.parse((r.params as any).id),b=z.object({expectedStatus:z.literal('PROPOSED'),reason}).parse(r.body),out=await transaction(db,async c=>idem(c,r,`control.${decision.toLowerCase()}`,proposalId,b,async()=>{const row=(await c.query('SELECT * FROM operational_control_requests WHERE id=$1 FOR UPDATE',[proposalId])).rows[0];if(!row)throw new OperationsError('OPERATIONAL_CONTROL_PROPOSAL_NOT_FOUND','Control proposal not found.',404);if(row.status!=='PROPOSED')throw new OperationsError('OPERATIONAL_CONTROL_DECISION_CONFLICT','Proposal is no longer pending.');if(row.proposed_by===r.actor!.id)throw new OperationsError('OPERATIONAL_MAKER_CHECKER_REQUIRED','An independent checker is required.');const decisionId=newId('ocd');await c.query('INSERT INTO operational_control_decisions(id,request_id,decision,decided_by,reason) VALUES($1,$2,$3,$4,$5)',[decisionId,row.id,decision,r.actor!.id,b.reason]);await c.query('UPDATE operational_control_requests SET status=$1,decided_at=now() WHERE id=$2',[decision,row.id]);if(decision==='APPROVED')await c.query('INSERT INTO operational_control_history(id,request_id,control_key,active,actor_id,reason,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[newId('och'),row.id,row.control_key,row.requested_active,r.actor!.id,b.reason,row.expires_at]);await evidence(c,r,decision==='APPROVED'?'OPERATIONAL_CONTROL_APPROVED':'OPERATIONAL_CONTROL_REJECTED','operational_control',row.id,{controlKey:row.control_key,requestedActive:row.requested_active});operationalMetrics.increment('operational_control_decisions_total',{decision:decision.toLowerCase(),control:row.control_key.toLowerCase()});return {status:200,body:{id:row.id,controlKey:row.control_key,status:decision,active:decision==='APPROVED'?row.requested_active:row.expected_active}};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}};
 app.post('/v1/platform/operations/control-proposals/:id/approve',{preHandler:[approve,rateLimit(limits,config,'operational-control-decision',20,60,r=>`platform:${r.actor?.id}`)]},(r,p)=>decide(r,p,'APPROVED'));
 app.post('/v1/platform/operations/control-proposals/:id/reject',{preHandler:[approve,rateLimit(limits,config,'operational-control-decision',20,60,r=>`platform:${r.actor?.id}`)]},(r,p)=>decide(r,p,'REJECTED'));
 const redisAvailable=async()=>{try{await Promise.race([limits.ping(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('redis timeout')),config.HEALTH_CHECK_TIMEOUT_MS))]);return true;}catch{return false;}};
 app.get('/v1/platform/operations/overview',{preHandler:[guard(db,config,'platform.operations.read'),overviewLimit]},async(r)=>{const one=async(sql:string)=>Number((await db.query(sql)).rows[0].count),age=async()=>{const row=(await db.query(`SELECT extract(epoch FROM now()-min(created_at))::int age FROM outbox_events WHERE status IN ('PENDING','PROCESSING')`)).rows[0];return row.age===null?null:Number(row.age);},body={outboxPending:await one(`SELECT count(*) FROM outbox_events WHERE status IN ('PENDING','PROCESSING')`),oldestPendingOutboxAgeSeconds:await age(),outboxFailed:await one(`SELECT count(*) FROM outbox_events WHERE status='FAILED'`),webhookPending:await one(`SELECT count(*) FROM webhook_deliveries WHERE status IN ('PENDING','PROCESSING')`),webhookFailed:await one(`SELECT count(*) FROM webhook_deliveries WHERE status='FAILED'`),notificationPending:await one(`SELECT count(*) FROM notification_delivery_jobs WHERE state IN ('PENDING','CLAIMED','DEFERRED','FAILED_RETRYABLE')`),notificationTerminal:await one(`SELECT count(*) FROM notification_delivery_jobs WHERE state='FAILED_TERMINAL'`),reconciliationExceptions:await one(`SELECT count(*) FROM reconciliation_exceptions WHERE status NOT IN ('RESOLVED','IGNORED')`),pendingSettlements:await one(`SELECT count(*) FROM settlement_batches WHERE status NOT IN ('COMPLETED','CANCELLED')`),openDisputes:await one(`SELECT count(*) FROM disputes WHERE status<>'CLOSED'`),openSupportCases:await one(`SELECT count(*) FROM support_cases WHERE status<>'CLOSED'`),activeIncidents:await one(`SELECT count(*) FROM operational_incidents WHERE state NOT IN ('RESOLVED','CLOSED')`),activeControls:(await Promise.all(controls.map(x=>isOperationalControlActive(db,x)))).filter(Boolean).length,dependencies:{postgresql:'available',redis:await redisAvailable()?'available':'unavailable'},externalProviders:{email:'disabled',sms:'disabled',payments:'sandbox'}};await db.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id,metadata) VALUES($1,$2,NULL,'OPERATIONAL_OVERVIEW_VIEWED','operations_overview',$1,$3)`,[newId('aud'),r.actor!.id,{activeIncidents:body.activeIncidents,activeControls:body.activeControls}]);return body;});
 app.get('/v1/platform/operations/metrics',{preHandler:[guard(db,config,'platform.metrics.read'),rateLimit(limits,config,'operational-metrics',60,60,r=>`platform:${r.actor?.id}`)]},async r=>{const counts={postgresPool:{total:db.totalCount,idle:db.idleCount,waiting:db.waitingCount},outboxPending:Number((await db.query(`SELECT count(*) FROM outbox_events WHERE status IN ('PENDING','PROCESSING')`)).rows[0].count),outboxFailed:Number((await db.query(`SELECT count(*) FROM outbox_events WHERE status='FAILED'`)).rows[0].count),webhookPending:Number((await db.query(`SELECT count(*) FROM webhook_deliveries WHERE status IN ('PENDING','PROCESSING')`)).rows[0].count),webhookFailed:Number((await db.query(`SELECT count(*) FROM webhook_deliveries WHERE status='FAILED'`)).rows[0].count),notificationPending:Number((await db.query(`SELECT count(*) FROM notification_delivery_jobs WHERE state IN ('PENDING','CLAIMED','DEFERRED','FAILED_RETRYABLE')`)).rows[0].count),notificationFailed:Number((await db.query(`SELECT count(*) FROM notification_delivery_jobs WHERE state='FAILED_TERMINAL'`)).rows[0].count),activeIncidents:Number((await db.query(`SELECT count(*) FROM operational_incidents WHERE state NOT IN ('RESOLVED','CLOSED')`)).rows[0].count),activeControls:(await Promise.all(controls.map(x=>isOperationalControlActive(db,x)))).filter(Boolean).length,reconciliationExceptions:Number((await db.query(`SELECT count(*) FROM reconciliation_exceptions WHERE status NOT IN ('RESOLVED','IGNORED')`)).rows[0].count),redisAvailable:await redisAvailable()};await db.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id) VALUES($1,$2,NULL,'PLATFORM_METRICS_VIEWED','operations_metrics',$1)`,[newId('aud'),r.actor!.id]);return {application:operationalMetrics.snapshot(),gauges:counts};});
}

export { controls as operationalControlKeys };
