import { createHash } from 'node:crypto';
import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Config } from '../config.js';
import type { Db } from '../db.js';
import { transaction } from '../db.js';
import { rateLimit,type RateLimitStore } from '../rateLimit.js';
import { apiError,authenticate,newId } from '../security.js';

class SupportError extends Error { constructor(readonly code:string,message:string,readonly status=409){super(message)} }
const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(',')}}`:JSON.stringify(value);
const sha=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const key=z.string().min(8).max(128).regex(/^[\x21-\x7e]+$/),id=z.string().min(3).max(80),cursor=z.string().max(300).refine(v=>{const parts=v.split('|');return parts.length===2&&z.iso.datetime().safeParse(parts[0]).success&&id.safeParse(parts[1]).success},{message:'Invalid cursor'}),page=z.object({limit:z.coerce.number().int().min(1).max(100).default(25),cursor:cursor.optional()}),dates=z.object({from:z.iso.datetime().optional(),to:z.iso.datetime().optional()}).refine(v=>!v.from||!v.to||v.from<v.to,{message:'from must precede to'}),message=z.object({message:z.string().trim().min(1).max(10000).refine(v=>!/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(v),'Control characters are not allowed.')}),reason=z.string().trim().min(3).max(1000);
const cursorParts=(value:string|undefined)=>value?value.split('|') as [string,string]:[null,null],nextCursor=(row:any)=>row?`${new Date(row.updated_at??row.created_at??row.occurred_at).toISOString()}|${row.id}`:null;
const categories=['ACCOUNT','ONBOARDING','PAYMENT','REFUND','SETTLEMENT','RECONCILIATION','API_INTEGRATION','WEBHOOK','SECURITY','OTHER'] as const,statuses=['OPEN','IN_PROGRESS','WAITING_ON_MERCHANT','RESOLVED','CLOSED'] as const,priorities=['LOW','NORMAL','HIGH','URGENT'] as const;
const view=(x:any)=>({id:x.id,reference:x.reference,merchantId:x.merchant_id,category:x.category,subject:x.subject,status:x.status,priority:x.priority,createdAt:x.created_at,updatedAt:x.updated_at,resolvedAt:x.resolved_at,closedAt:x.closed_at});
const fail=(r:FastifyRequest,p:FastifyReply,e:unknown)=>{if(e instanceof z.ZodError)return p.code(400).send(apiError(r,'VALIDATION_ERROR','The request is invalid.'));if(e instanceof SupportError)return p.code(e.status).send(apiError(r,e.code,e.message));throw e};
export async function registerPlatformRoutes(app:FastifyInstance,config:Config,db:Db,limits:RateLimitStore){
 const guard=(domain:'merchant'|'platform',permission:string)=>async(r:FastifyRequest,p:FastifyReply)=>{if(r.headers.authorization){p.code(403).send(apiError(r,'FORBIDDEN','A browser session is required.'));return;}await authenticate(db,config,r,p);if(p.sent)return;if(r.actor?.authType==='apiKey'){p.code(403).send(apiError(r,'FORBIDDEN','A browser session is required.'));return;}if(domain==='platform'&&(r.actor?.merchantId!==null||r.actor?.role!=='PLATFORM_ADMIN')){p.code(403).send(apiError(r,'PLATFORM_PERMISSION_DENIED','Platform staff authority is required.'));return;}if(domain==='merchant'&&!r.actor?.merchantId){p.code(403).send(apiError(r,'FORBIDDEN','Merchant authority is required.'));return;}if(!r.actor?.permissions.includes(permission)){p.code(403).send(apiError(r,domain==='platform'?'PLATFORM_PERMISSION_DENIED':'FORBIDDEN','You do not have permission to perform this action.'));}};
 const platform=(permission:string):any[]=>[guard('platform',permission)];
 const merchant=(permission:string):any[]=>[guard('merchant',permission)];
 const idem=async(c:any,scope:string,op:string,k:string,body:unknown,work:()=>Promise<{status:number,body:any}>)=>{await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${scope}:${op}:${k}`]);const h=sha(body),old=(await c.query('SELECT * FROM support_idempotency WHERE authority_scope=$1 AND operation=$2 AND idempotency_key=$3',[scope,op,k])).rows[0];if(old){if(old.request_sha256!==h)throw new SupportError('IDEMPOTENCY_CONFLICT','The idempotency key was reused with different input.');return {status:old.response_status,body:old.response_body};}const out=await work();await c.query('INSERT INTO support_idempotency(authority_scope,operation,idempotency_key,request_sha256,response_status,response_body) VALUES($1,$2,$3,$4,$5,$6)',[scope,op,k,h,out.status,out.body]);return out;};
 const event=async(c:any,r:FastifyRequest,action:string,caseId:string,merchantId:string,metadata:object={})=>{await c.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id,metadata) VALUES($1,$2,$3,$4,'support_case',$5,$6)`,[newId('aud'),r.actor!.id,merchantId,action,caseId,metadata]);await c.query(`INSERT INTO outbox_events(id,event_type,aggregate_type,aggregate_id,payload,deduplication_key) VALUES($1,$2,'support_case',$3,$4,$5)`,[newId('obx'),`support.${action.toLowerCase()}`,caseId,{caseId,merchantId,...metadata},`${action}:${caseId}:${newId('evt')}`]);};
 const createLimit=rateLimit(limits,config,'support-case-create',10,3600,r=>`${r.actor?.merchantId}:${r.actor?.id}`),replyLimit=rateLimit(limits,config,'support-reply',30,3600,r=>`${r.actor?.merchantId??'platform'}:${r.actor?.id}`),searchLimit=rateLimit(limits,config,'platform-search',60,60,r=>r.actor?.id);

 app.post('/v1/support/cases',{preHandler:[...merchant('support:write'),createLimit]},async(r,p)=>{try{const b=z.object({category:z.enum(categories),subject:z.string().trim().min(3).max(160),message:message.shape.message}).parse(r.body),k=key.parse(r.headers['idempotency-key']);const out=await transaction(db,async c=>idem(c,`merchant:${r.actor!.merchantId}`,'case.create',k,b,async()=>{const caseId=newId('sup'),ref=`SUP-${caseId.slice(-12).toUpperCase()}`,row=(await c.query(`INSERT INTO support_cases(id,reference,merchant_id,created_by,category,subject) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[caseId,ref,r.actor!.merchantId,r.actor!.id,b.category,b.subject])).rows[0];await c.query(`INSERT INTO support_public_messages(id,case_id,merchant_id,author_id,author_domain,body) VALUES($1,$2,$3,$4,'MERCHANT',$5)`,[newId('msg'),caseId,r.actor!.merchantId,r.actor!.id,b.message]);await c.query(`INSERT INTO support_status_history(id,case_id,merchant_id,actor_id,from_status,to_status,reason) VALUES($1,$2,$3,$4,NULL,'OPEN','Case created')`,[newId('sth'),caseId,r.actor!.merchantId,r.actor!.id]);await event(c,r,'SUPPORT_CASE_CREATED',caseId,r.actor!.merchantId!,{category:b.category});return {status:201,body:view(row)};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});
 app.get('/v1/support/cases',{preHandler:merchant('support:read')},async r=>{const q=page.parse(r.query),[cursorAt,cursorId]=cursorParts(q.cursor),x=await db.query(`SELECT * FROM support_cases WHERE merchant_id=$1 AND ($2::timestamptz IS NULL OR (created_at,id)<($2,$3)) ORDER BY created_at DESC,id DESC LIMIT $4`,[r.actor!.merchantId,cursorAt,cursorId,q.limit+1]);return {data:x.rows.slice(0,q.limit).map(view),nextCursor:x.rows.length>q.limit?nextCursor(x.rows[q.limit-1]):null};});
 app.get('/v1/support/cases/:id',{preHandler:merchant('support:read')},async(r,p)=>{const x=await db.query('SELECT * FROM support_cases WHERE id=$1 AND merchant_id=$2',[id.parse((r.params as any).id),r.actor!.merchantId]);if(!x.rowCount)return p.code(404).send(apiError(r,'SUPPORT_CASE_NOT_FOUND','Support case not found.'));const msgs=await db.query('SELECT id,author_id,author_domain,body,created_at FROM support_public_messages WHERE case_id=$1 AND merchant_id=$2 ORDER BY created_at,id',[x.rows[0].id,r.actor!.merchantId]);return {...view(x.rows[0]),messages:msgs.rows};});
 app.post('/v1/support/cases/:id/replies',{preHandler:[...merchant('support:write'),replyLimit]},async(r,p)=>{try{const b=message.parse(r.body),caseId=id.parse((r.params as any).id),k=key.parse(r.headers['idempotency-key']);const out=await transaction(db,async c=>idem(c,`merchant:${r.actor!.merchantId}`,'reply.create',k,{caseId,...b},async()=>{const locked=(await c.query('SELECT * FROM support_cases WHERE id=$1 AND merchant_id=$2 FOR UPDATE',[caseId,r.actor!.merchantId])).rows[0];if(!locked)throw new SupportError('SUPPORT_CASE_NOT_FOUND','Support case not found.',404);if(locked.status==='CLOSED')throw new SupportError('SUPPORT_INVALID_TRANSITION','Closed cases cannot receive replies.');const msg=(await c.query(`INSERT INTO support_public_messages(id,case_id,merchant_id,author_id,author_domain,body) VALUES($1,$2,$3,$4,'MERCHANT',$5) RETURNING id,author_id,author_domain,body,created_at`,[newId('msg'),caseId,r.actor!.merchantId,r.actor!.id,b.message])).rows[0];await c.query('UPDATE support_cases SET last_merchant_activity_at=now(),updated_at=now() WHERE id=$1',[caseId]);await event(c,r,'SUPPORT_PUBLIC_REPLY_CREATED',caseId,r.actor!.merchantId!);return {status:201,body:msg};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});
 app.post('/v1/support/cases/:id/status',{preHandler:merchant('support:write')},async(r,p)=>p.code(403).send(apiError(r,'SUPPORT_PLATFORM_TRANSITION_REQUIRED','Closing, resolving, and reopening support cases is restricted to platform support staff.')));

 app.get('/v1/platform/support/cases',{preHandler:[...platform('platform.support.read'),searchLimit]},async r=>{const q=page.merge(dates).extend({merchantId:z.string().max(80).optional(),status:z.enum(statuses).optional(),priority:z.enum(priorities).optional()}).parse(r.query),[cursorAt,cursorId]=cursorParts(q.cursor),x=await db.query(`SELECT * FROM support_cases WHERE ($1::text IS NULL OR merchant_id=$1) AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR priority=$3) AND ($4::timestamptz IS NULL OR (updated_at,id)<($4,$5)) AND ($6::timestamptz IS NULL OR created_at>=$6) AND ($7::timestamptz IS NULL OR created_at<$7) ORDER BY updated_at DESC,id DESC LIMIT $8`,[q.merchantId??null,q.status??null,q.priority??null,cursorAt,cursorId,q.from??null,q.to??null,q.limit+1]);return {data:x.rows.slice(0,q.limit).map(view),nextCursor:x.rows.length>q.limit?nextCursor(x.rows[q.limit-1]):null};});
 app.get('/v1/platform/support/cases/:id',{preHandler:platform('platform.support.read')},async(r,p)=>{const caseId=id.parse((r.params as any).id),x=(await db.query('SELECT * FROM support_cases WHERE id=$1',[caseId])).rows[0];if(!x)return p.code(404).send(apiError(r,'SUPPORT_CASE_NOT_FOUND','Support case not found.'));const [messages,notes,status,assignments,priority]=await Promise.all([db.query('SELECT id,author_id,author_domain,body,created_at FROM support_public_messages WHERE case_id=$1 ORDER BY created_at,id',[caseId]),db.query('SELECT id,author_id,body,created_at FROM support_internal_notes WHERE case_id=$1 ORDER BY created_at,id',[caseId]),db.query('SELECT * FROM support_status_history WHERE case_id=$1 ORDER BY created_at,id',[caseId]),db.query('SELECT * FROM support_assignment_history WHERE case_id=$1 ORDER BY created_at,id',[caseId]),db.query('SELECT * FROM support_priority_history WHERE case_id=$1 ORDER BY created_at,id',[caseId])]);return {...view(x),messages:messages.rows,internalNotes:notes.rows,statusHistory:status.rows,assignmentHistory:assignments.rows,priorityHistory:priority.rows};});
 const platformText=(path:string,internal:boolean)=>app.post(path,{preHandler:[...platform('platform.support.reply'),replyLimit]},async(r,p)=>{try{const b=message.parse(r.body),caseId=id.parse((r.params as any).id),k=key.parse(r.headers['idempotency-key']),table=internal?'support_internal_notes':'support_public_messages',op=internal?'note.create':'reply.create';const out=await transaction(db,async c=>idem(c,`platform:${r.actor!.id}`,op,k,{caseId,...b},async()=>{const locked=(await c.query('SELECT * FROM support_cases WHERE id=$1 FOR UPDATE',[caseId])).rows[0];if(!locked)throw new SupportError('SUPPORT_CASE_NOT_FOUND','Support case not found.',404);const msgId=newId(internal?'note':'msg');if(internal)await c.query(`INSERT INTO ${table}(id,case_id,merchant_id,author_id,body) VALUES($1,$2,$3,$4,$5)`,[msgId,caseId,locked.merchant_id,r.actor!.id,b.message]);else await c.query(`INSERT INTO ${table}(id,case_id,merchant_id,author_id,author_domain,body) VALUES($1,$2,$3,$4,'PLATFORM',$5)`,[msgId,caseId,locked.merchant_id,r.actor!.id,b.message]);await c.query('UPDATE support_cases SET last_staff_activity_at=now(),updated_at=now() WHERE id=$1',[caseId]);await event(c,r,internal?'SUPPORT_INTERNAL_NOTE_CREATED':'SUPPORT_PUBLIC_REPLY_CREATED',caseId,locked.merchant_id);return {status:201,body:{id:msgId,created:true}};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});
 platformText('/v1/platform/support/cases/:id/replies',false);platformText('/v1/platform/support/cases/:id/internal-notes',true);
 app.post('/v1/platform/support/cases/:id/assign',{preHandler:platform('platform.support.assign')},async(r,p)=>{try{const b=z.object({staffId:id,reason,expectedAssigneeId:id.nullable().optional()}).parse(r.body),caseId=id.parse((r.params as any).id),k=key.parse(r.headers['idempotency-key']);const out=await transaction(db,async c=>idem(c,`platform:${r.actor!.id}`,`case.assign:${caseId}`,k,b,async()=>{const x=(await c.query('SELECT * FROM support_cases WHERE id=$1 FOR UPDATE',[caseId])).rows[0];if(!x)throw new SupportError('SUPPORT_CASE_NOT_FOUND','Support case not found.',404);const eligible=await c.query(`SELECT 1 FROM users WHERE id=$1 AND merchant_id IS NULL AND role='PLATFORM_ADMIN' AND status='ACTIVE' AND permissions @> ARRAY['platform.support.read']`,[b.staffId]);if(!eligible.rowCount)throw new SupportError('SUPPORT_ASSIGNEE_INELIGIBLE','The selected staff member is not eligible for support assignment.',422);if(x.assigned_to!==(b.expectedAssigneeId??null))throw new SupportError('SUPPORT_ASSIGNMENT_CONFLICT','The case assignment changed.');const row=(await c.query('UPDATE support_cases SET assigned_to=$1,updated_at=now() WHERE id=$2 RETURNING *',[b.staffId,caseId])).rows[0];await c.query('INSERT INTO support_assignment_history(id,case_id,merchant_id,actor_id,from_staff_id,to_staff_id,reason) VALUES($1,$2,$3,$4,$5,$6,$7)',[newId('ash'),caseId,x.merchant_id,r.actor!.id,x.assigned_to,b.staffId,b.reason]);await event(c,r,'SUPPORT_ASSIGNED',caseId,x.merchant_id,{staffId:b.staffId});return {status:200,body:{...view(row),assignedTo:b.staffId}};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});
 app.post('/v1/platform/support/cases/:id/status',{preHandler:platform('platform.support.manage')},async(r,p)=>{try{const b=z.object({status:z.enum(statuses),reason,expectedStatus:z.enum(statuses).default('OPEN')}).parse(r.body),caseId=id.parse((r.params as any).id),k=key.parse(r.headers['idempotency-key']);const out=await transaction(db,async c=>idem(c,`platform:${r.actor!.id}`,`case.status:${caseId}`,k,b,async()=>{const x=(await c.query('SELECT * FROM support_cases WHERE id=$1 FOR UPDATE',[caseId])).rows[0];if(!x)throw new SupportError('SUPPORT_CASE_NOT_FOUND','Support case not found.',404);if(x.status!==b.expectedStatus)throw new SupportError('SUPPORT_CONCURRENT_MODIFICATION','The support case status changed.');const row=(await c.query(`UPDATE support_cases SET status=$1,updated_at=now(),resolved_at=CASE WHEN $1='RESOLVED' THEN now() WHEN $1='OPEN' THEN NULL ELSE resolved_at END,closed_at=CASE WHEN $1='CLOSED' THEN now() WHEN $1='OPEN' THEN NULL ELSE closed_at END WHERE id=$2 RETURNING *`,[b.status,caseId])).rows[0];await c.query('INSERT INTO support_status_history(id,case_id,merchant_id,actor_id,from_status,to_status,reason) VALUES($1,$2,$3,$4,$5,$6,$7)',[newId('sth'),caseId,x.merchant_id,r.actor!.id,x.status,b.status,b.reason]);await event(c,r,'SUPPORT_STATUS_CHANGED',caseId,x.merchant_id,{from:x.status,to:b.status});return {status:200,body:view(row)};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});
 app.post('/v1/platform/support/cases/:id/priority',{preHandler:platform('platform.support.manage')},async(r,p)=>{try{const b=z.object({priority:z.enum(priorities),reason,expectedPriority:z.enum(priorities).default('NORMAL')}).parse(r.body),caseId=id.parse((r.params as any).id),k=key.parse(r.headers['idempotency-key']);const out=await transaction(db,async c=>idem(c,`platform:${r.actor!.id}`,`case.priority:${caseId}`,k,b,async()=>{const x=(await c.query('SELECT * FROM support_cases WHERE id=$1 FOR UPDATE',[caseId])).rows[0];if(!x)throw new SupportError('SUPPORT_CASE_NOT_FOUND','Support case not found.',404);if(x.priority!==b.expectedPriority)throw new SupportError('SUPPORT_CONCURRENT_MODIFICATION','The support case priority changed.');const row=(await c.query('UPDATE support_cases SET priority=$1,updated_at=now() WHERE id=$2 RETURNING *',[b.priority,caseId])).rows[0];await c.query('INSERT INTO support_priority_history(id,case_id,merchant_id,actor_id,from_priority,to_priority,reason) VALUES($1,$2,$3,$4,$5,$6,$7)',[newId('prh'),caseId,x.merchant_id,r.actor!.id,x.priority,b.priority,b.reason]);await event(c,r,'SUPPORT_PRIORITY_CHANGED',caseId,x.merchant_id,{from:x.priority,to:b.priority});return {status:200,body:view(row)};}));return p.code(out.status).send(out.body);}catch(e){return fail(r,p,e)}});

 app.get('/v1/platform/merchants',{preHandler:[...platform('platform.merchants.read'),searchLimit]},async r=>{const q=page.parse(r.query),[cursorAt,cursorId]=cursorParts(q.cursor),x=await db.query(`SELECT m.id,m.name,m.environment,m.created_at,(SELECT status FROM onboarding_applications a WHERE a.merchant_id=m.id ORDER BY a.created_at DESC LIMIT 1) onboarding_status,(SELECT count(*)::int FROM users u WHERE u.merchant_id=m.id AND u.status='ACTIVE') team_member_count,(SELECT count(*)::int FROM support_cases s WHERE s.merchant_id=m.id AND s.status<>'CLOSED') open_support_cases FROM merchants m WHERE ($1::timestamptz IS NULL OR (m.created_at,m.id)<($1,$2)) ORDER BY m.created_at DESC,m.id DESC LIMIT $3`,[cursorAt,cursorId,q.limit+1]);return {data:x.rows.slice(0,q.limit),nextCursor:x.rows.length>q.limit?nextCursor(x.rows[q.limit-1]):null};});
 app.get('/v1/platform/merchants/:id',{preHandler:platform('platform.merchants.read')},async(r,p)=>{const merchantId=id.parse((r.params as any).id),x=(await db.query(`SELECT m.id,m.name,m.environment,m.created_at,b.registration_number_masked,b.tax_identifier_masked,a.status onboarding_status,(SELECT count(*)::int FROM users WHERE merchant_id=m.id AND status='ACTIVE') team_member_count,(SELECT count(*)::int FROM payments WHERE merchant_id=m.id) transaction_count,(SELECT count(*)::int FROM refunds WHERE merchant_id=m.id) refund_count,(SELECT count(*)::int FROM settlement_batches WHERE merchant_id=m.id) settlement_count,(SELECT count(*)::int FROM reconciliation_exceptions WHERE merchant_id=m.id AND status IN ('OPEN','UNDER_REVIEW')) reconciliation_exception_count,(SELECT count(*)::int FROM support_cases WHERE merchant_id=m.id AND status<>'CLOSED') open_support_cases FROM merchants m LEFT JOIN onboarding_applications a ON a.id=(SELECT id FROM onboarding_applications WHERE merchant_id=m.id ORDER BY created_at DESC LIMIT 1) LEFT JOIN onboarding_business_profiles b ON b.application_id=a.id WHERE m.id=$1`,[merchantId])).rows[0];return x??p.code(404).send(apiError(r,'MERCHANT_NOT_FOUND','Merchant not found.'));});
 app.get('/v1/platform/transactions',{preHandler:[...platform('platform.transactions.read'),searchLimit]},async r=>{const q=page.merge(dates).extend({merchantId:z.string().max(80).optional(),status:z.string().max(40).optional(),currency:z.string().regex(/^[A-Z]{3}$/).optional()}).parse(r.query),[cursorAt,cursorId]=cursorParts(q.cursor),x=await db.query(`SELECT id,merchant_id,reference,merchant_reference,status,channel,provider_name,gross_minor,fee_minor,tax_minor,currency,refunded_minor,reconciliation_state,settlement_state,created_at,updated_at FROM payments WHERE ($1::text IS NULL OR merchant_id=$1) AND ($2::text IS NULL OR status=$2) AND ($3::char(3) IS NULL OR currency=$3) AND ($4::timestamptz IS NULL OR (created_at,id)<($4,$5)) AND ($6::timestamptz IS NULL OR created_at>=$6) AND ($7::timestamptz IS NULL OR created_at<$7) ORDER BY created_at DESC,id DESC LIMIT $8`,[q.merchantId??null,q.status??null,q.currency??null,cursorAt,cursorId,q.from??null,q.to??null,q.limit+1]);return {data:x.rows.slice(0,q.limit),nextCursor:x.rows.length>q.limit?nextCursor(x.rows[q.limit-1]):null};});
 app.get('/v1/platform/refunds',{preHandler:platform('platform.refunds.read')},async r=>{const q=page.parse(r.query);return {data:(await db.query(`SELECT r.id,r.merchant_id,r.reference,r.payment_id,r.amount_minor,r.status,r.reason,r.requested_by,r.decided_at,r.created_at,p.currency,p.reference payment_reference FROM refunds r JOIN payments p ON p.id=r.payment_id ORDER BY r.created_at DESC,r.id DESC LIMIT $1`,[q.limit])).rows};});
 app.get('/v1/platform/settlements',{preHandler:platform('platform.settlements.read')},async r=>({data:(await db.query(`SELECT id,merchant_id,currency,period_start,period_end,status,gross_minor,refunds_minor,fees_minor,net_minor,created_at,external_transfer_executed FROM settlement_batches ORDER BY created_at DESC,id DESC LIMIT $1`,[page.parse(r.query).limit])).rows,sandboxOnly:true,payoutExecuted:false}));
 app.get('/v1/platform/reconciliation/exceptions',{preHandler:platform('platform.reconciliation.read')},async r=>({data:(await db.query(`SELECT id,run_id,merchant_id,classification,source_reference,status,created_at,resolved_at FROM reconciliation_exceptions ORDER BY created_at DESC,id DESC LIMIT $1`,[page.parse(r.query).limit])).rows}));
 app.get('/v1/platform/audit-events',{preHandler:[...platform('platform.audit.read'),searchLimit]},async r=>{const q=page.parse(r.query),[cursorAt,cursorId]=cursorParts(q.cursor),rows=await transaction(db,async c=>{const found=(await c.query(`SELECT id,actor_id,merchant_id,action,resource_type,resource_id,metadata,occurred_at FROM audit_events WHERE ($1::timestamptz IS NULL OR (occurred_at,id)<($1,$2)) ORDER BY occurred_at DESC,id DESC LIMIT $3`,[cursorAt,cursorId,q.limit+1])).rows;await c.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id,metadata) VALUES($1,$2,NULL,'PLATFORM_AUDIT_LOG_VIEWED','audit_query',$1,$3)`,[newId('aud'),r.actor!.id,{resultCount:Math.min(found.length,q.limit)}]);return found;});return {data:rows.slice(0,q.limit).map((x:any)=>({...x,metadata:Object.fromEntries(Object.entries(x.metadata??{}).filter(([k])=>!/password|token|secret|body|storage|cipher|stack|error/i.test(k)))})),nextCursor:rows.length>q.limit?nextCursor(rows[q.limit-1]):null};});
 app.get('/v1/platform/health',{preHandler:platform('platform.health.read')},async()=>{await Promise.all([db.query('SELECT 1'),limits.ping()]);return {status:'ready',dependencies:{database:'available',rateLimitStore:'available'},timestamp:new Date().toISOString()};});
}
