import { cloneElement } from 'react';
import { Link } from 'react-router-dom';

const PAYMENT_METHODS = [
  {
    label: 'Airtel Money',
    icon: <img src="/brands/airtel-money.svg" alt="Airtel Money" className="h-12 w-12 object-contain" />,
  },
  {
    label: 'TNM Mpamba',
    icon: <img src="/brands/tnm-mpamba.svg" alt="TNM Mpamba" className="h-12 w-12 object-contain" />,
  },
  {
    label: 'Visa',
    icon: <img src="/brands/visa.svg" alt="Visa" className="h-12 w-12 object-contain" />,
  },
  {
    label: 'Mastercard',
    icon: <img src="/brands/mastercard.svg" alt="Mastercard" className="h-12 w-12 object-contain" />,
  },
  {
    label: 'National Switch',
    icon: (
      <svg className="h-12 w-12 text-blue-300" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
      </svg>
    ),
  },
];

const BENEFITS = [
  {
    title: 'One integration',
    body: 'Accept configured digital payment methods through a single, unified GiantPay integration.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
      </svg>
    ),
  },
  {
    title: 'Clear transaction evidence',
    body: 'Every payment carries a trusted backend status, full event history, and real-time reconciliation state.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
      </svg>
    ),
  },
  {
    title: 'Reconciliation built in',
    body: 'Match transactions against settlement records automatically and surface exceptions, without manual spreadsheets.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" />
      </svg>
    ),
  },
  {
    title: 'Reporting that holds up',
    body: 'Export transaction, fee, refund, and settlement reports generated by the backend ledger, not the browser.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
      </svg>
    ),
  },
];

const FAQS = [
  {
    q: 'Which payment methods can I accept in Malawi?',
    a: 'GiantPay is designed to support Airtel Money, TNM Mpamba, Visa & Mastercard, and direct bank transfers via the National Switch. You can test each of these payment flows today in our sandbox, ahead of full production rollout.',
  },
  {
    q: 'How do I get started?',
    a: 'Register an account, complete your KYC/KYB business verification, and start testing immediately in our full sandbox environment.',
  },
  {
    q: 'Can I test before going live?',
    a: 'Yes — every merchant receives sandbox API keys and simulated checkout tools to test payment flows, webhooks, and refunds end-to-end.',
  },
  {
    q: 'How are payouts and settlements handled?',
    a: 'In sandbox, you can simulate settlement batches and reconciliation reports against your test transactions. Live payouts to your Malawian business bank account will be available once provider and regulatory onboarding is complete.',
  },
];

export default function LandingPage() {
  return (
    <>
      {/* ── Rich Fintech Hero Section ── */}
      <section
        className="relative overflow-hidden text-white"
        style={{ background: 'linear-gradient(160deg, #061428 0%, #0B2445 32%, #0d2d5e 65%, #071a38 100%)' }}
      >
        <div className="relative z-10 mx-auto max-w-6xl px-4 pt-16 pb-16 sm:px-6 sm:pt-24 sm:pb-20">
          <div className="grid items-center gap-12 lg:grid-cols-2">
            {/* Left column — copy + actions */}
            <div className="text-center lg:text-left">
              <h1 className="mx-auto max-w-xl text-3xl font-extrabold tracking-tight text-white sm:text-5xl md:text-6xl leading-[1.15] lg:mx-0">
                Unified payments.{' '}
                <span style={{ color: '#ff5263' }}>One integration.</span>
              </h1>

              <p className="mx-auto mt-5 max-w-xl text-sm sm:text-base md:text-lg leading-relaxed text-white/85 lg:mx-0">
                GiantPay helps businesses and digital platforms in Malawi accept and manage configured digital payment
                methods through one secure integration, with clear transaction evidence, developer tools, reconciliation
                and reporting.
              </p>

              <div className="mt-8 flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-3.5 sm:gap-6 w-full">
                <Link
                  to="/register"
                  className="w-full sm:w-auto text-center rounded-xl bg-white px-7 py-3 text-sm sm:text-base font-semibold text-[#1a6dcc] shadow-lg transition-all duration-300 ease-in-out hover:scale-105 hover:shadow-xl active:scale-[0.98]"
                >
                  Create sandbox account
                </Link>
                <Link
                  to="/developers/overview"
                  className="group inline-flex items-center gap-1.5 text-sm sm:text-base font-semibold text-white transition-all duration-300 ease-in-out hover:gap-2.5"
                >
                  Explore Developer Tools
                  <span aria-hidden="true" className="transition-transform duration-300 ease-in-out group-hover:translate-x-1">→</span>
                </Link>
              </div>
            </div>

            {/* Right column — product visual */}
            <div className="relative mx-auto w-full max-w-md lg:max-w-none">
              <div
                aria-hidden="true"
                className="absolute -inset-6 rounded-[2rem] bg-white/10 blur-2xl"
              />
              <img
                src="/hero/hero-payment-phone.jpg"
                alt="A customer completing a contactless mobile payment"
                className="relative w-full rounded-3xl object-cover shadow-2xl"
                style={{ aspectRatio: '4 / 3' }}
              />
            </div>
          </div>

          {/* Payment method logos */}
          <div className="mt-14 pt-8 border-t border-white/20 flex flex-col items-center gap-4 w-full">
            <p className="text-[10px] uppercase font-semibold tracking-[0.2em] text-white/60">
              Designed for local payment integrations
            </p>
            <div className="w-full max-w-3xl overflow-hidden">
              <div
                className="flex w-max items-center gap-3 animate-marquee-ltr motion-reduce:animate-none"
                aria-label="Planned payment methods"
              >
                {[0, 1].map((copy) =>
                  PAYMENT_METHODS.map((method) => (
                    <div
                      key={`${copy}-${method.label}`}
                      aria-hidden={copy === 1}
                      className="flex items-center px-3 py-2"
                    >
                      <span className="inline-flex h-16 w-16 shrink-0 animate-pulse items-center justify-center">
                        {copy === 1 && method.icon.type === 'img'
                          ? cloneElement(method.icon, { alt: '' })
                          : method.icon}
                      </span>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── How GiantPay Works ── */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="text-center max-w-2xl mx-auto">
          <p className="text-xs font-bold uppercase tracking-widest text-blue-600">Simple 3-step setup</p>
          <h2 className="mt-2 text-2xl sm:text-3xl font-bold tracking-tight text-[var(--color-navy-900)]">
            How GiantPay works
          </h2>
          <p className="mt-2 text-sm text-[var(--color-neutral-600)]">
            From registration to sandbox testing in just three straightforward steps.
          </p>
        </div>

        <ol className="mx-auto mt-12 grid max-w-4xl gap-6 sm:grid-cols-3">
          {[
            {
              step: '1',
              title: 'Register & verify',
              body: 'Submit your business profile and KYC/KYB registration details for rapid compliance review.',
            },
            {
              step: '2',
              title: 'Integrate & test',
              body: 'Build against our complete sandbox using hosted payment links or REST API keys.',
            },
            {
              step: '3',
              title: 'Go live',
              body: 'Move from sandbox to production once your integration is verified and provider onboarding is complete.',
            },
          ].map((item) => (
            <li
              key={item.step}
              className="group relative rounded-2xl border border-[var(--color-neutral-200)] bg-white p-6 text-center shadow-sm transition-all duration-200 hover:-translate-y-1 hover:shadow-md"
            >
              <span className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-base font-bold text-blue-600 group-hover:bg-blue-600 group-hover:text-white transition-colors duration-200">
                {item.step}
              </span>
              <h3 className="mt-4 text-base font-semibold text-[var(--color-navy-900)]">{item.title}</h3>
              <p className="mt-2 text-xs sm:text-sm leading-relaxed text-[var(--color-neutral-600)]">{item.body}</p>
            </li>
          ))}
        </ol>
      </section>

      {/* ── Built for Merchants and Developers ── */}
      <section className="bg-[var(--color-neutral-50)] py-16 sm:py-20 border-y border-[var(--color-neutral-200)]">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="text-center max-w-2xl mx-auto">
            <p className="text-xs font-bold uppercase tracking-widest text-blue-600">Enterprise Ready</p>
            <h2 className="mt-2 text-2xl sm:text-3xl font-bold tracking-tight text-[var(--color-navy-900)]">
              Built for merchants and developers
            </h2>
            <p className="mt-2 text-sm text-[var(--color-neutral-600)]">
              Engineered with reliability, financial auditability, and ease of integration at its core.
            </p>
          </div>

          <div className="mt-12 grid gap-5 sm:grid-cols-2">
            {BENEFITS.map((b) => (
              <div
                key={b.title}
                className="flex items-start gap-4 rounded-2xl border border-[var(--color-neutral-200)] bg-white p-6 shadow-sm transition-all duration-200 hover:shadow-md"
              >
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-blue-50">
                  {b.icon}
                </div>
                <div>
                  <h3 className="text-base font-semibold text-[var(--color-navy-900)]">{b.title}</h3>
                  <p className="mt-1.5 text-xs sm:text-sm leading-relaxed text-[var(--color-neutral-600)]">{b.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Developer Experience Section ── */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="rounded-3xl border border-[var(--color-neutral-200)] bg-[var(--color-navy-950)] text-white p-6 sm:p-10 lg:p-12 overflow-hidden relative">
          {/* Subtle glow */}
          <div
            aria-hidden="true"
            className="pointer-events-none absolute top-0 right-0 h-[350px] w-[350px] rounded-full"
            style={{
              background: 'radial-gradient(circle, rgba(26,109,204,0.2) 0%, transparent 70%)',
            }}
          />

          <div className="relative z-10 grid gap-8 lg:grid-cols-2 lg:items-center">
            <div>
              <div className="inline-flex items-center gap-2 rounded-lg bg-blue-500/10 border border-blue-400/20 px-3 py-1 text-xs font-semibold text-blue-300 mb-4">
                <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                </svg>
                Developer-First API
              </div>
              <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
                Clean, predictable APIs and webhooks
              </h2>
              <p className="mt-4 text-sm sm:text-base leading-relaxed text-white/70">
                Sandbox API keys, webhooks with delivery history, idempotent requests, and documentation with
                cURL, JavaScript/TypeScript and PHP examples — all built around the same trusted-status model the hosted
                checkout uses.
              </p>
              <div className="mt-6 flex flex-wrap gap-3">
                <Link
                  to="/developers/overview"
                  className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow hover:bg-blue-500 transition-colors"
                >
                  View Developer Docs
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                  </svg>
                </Link>
                <Link
                  to="/register"
                  className="inline-flex items-center rounded-xl border border-white/20 bg-white/5 px-5 py-2.5 text-sm font-semibold text-white hover:bg-white/10 transition-colors"
                >
                  Get API Keys
                </Link>
              </div>
            </div>

            {/* Code / API Snippet Preview */}
            <div className="rounded-2xl border border-white/10 bg-black/40 p-4 sm:p-5 backdrop-blur-md overflow-x-auto">
              <div className="flex items-center justify-between pb-3 border-b border-white/10 text-xs text-white/50">
                <div className="flex items-center gap-1.5">
                  <span className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
                  <span className="h-2.5 w-2.5 rounded-full bg-amber-500/80" />
                  <span className="h-2.5 w-2.5 rounded-full bg-emerald-500/80" />
                  <span className="ml-2 font-mono text-[11px] text-white/60">POST /v1/checkout/sessions</span>
                </div>
                <span className="font-mono text-[10px] text-emerald-400">201 Created</span>
              </div>
              <pre className="mt-3 font-mono text-xs text-blue-200 leading-relaxed overflow-x-auto">
{`{
  "reference": "gp_req_91b7e4c2",
  "amount": 2500000,
  "currency": "MWK",
  "channels": ["AIRTEL_MONEY", "TNM_MPAMBA", "CARD"],
  "status": "INITIATED",
  "checkout_url": "https://pay.giantpay.mw/checkout/tok_..."
}`}
              </pre>
            </div>
          </div>
        </div>
      </section>

      {/* ── Frequently Asked Questions ── */}
      <section className="border-t border-[var(--color-neutral-200)] py-16 sm:py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <div className="text-center mb-10">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-[var(--color-navy-900)]">
              Frequently asked questions
            </h2>
            <p className="mt-2 text-sm text-[var(--color-neutral-600)]">
              Everything you need to know about payments, regulatory alignment, and testing.
            </p>
          </div>

          <dl className="flex flex-col gap-4">
            {FAQS.map((faq) => (
              <div
                key={faq.q}
                className="rounded-2xl border border-[var(--color-neutral-200)] bg-white p-5 sm:p-6 shadow-sm"
              >
                <dt className="font-semibold text-sm sm:text-base text-[var(--color-navy-900)]">{faq.q}</dt>
                <dd className="mt-2 text-xs sm:text-sm leading-relaxed text-[var(--color-neutral-600)]">{faq.a}</dd>
              </div>
            ))}
          </dl>
        </div>
      </section>
    </>
  );
}
