import { Link } from 'react-router-dom';
import { MARK_SRC } from '@/assets/brand';

const BENEFITS = [
  {
    title: 'One integration',
    body: 'Accept configured digital payment methods through a single, unified GiantPay integration.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
      </svg>
    ),
  },
  {
    title: 'Clear transaction evidence',
    body: 'Every payment carries a trusted backend status, full event history, and real-time reconciliation state.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
      </svg>
    ),
  },
  {
    title: 'Reconciliation built in',
    body: 'Match transactions automatically against provider and settlement records without manual spreadsheets.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" />
      </svg>
    ),
  },
  {
    title: 'Reporting that holds up',
    body: 'Export transaction, fee, refund, and settlement reports generated by the backend ledger, not the browser.',
    icon: (
      <svg className="h-6 w-6 text-blue-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
      </svg>
    ),
  },
];

const FAQS = [
  {
    q: 'Which payment methods can I accept in Malawi?',
    a: 'Available channels include Airtel Money, TNM Mpamba, Visa & Mastercard, and direct bank transfers via the National Switch. Channels are activated based on your merchant account tier.',
  },
  {
    q: 'How do I get started?',
    a: 'Register an account, complete your KYC/KYB business verification, and test immediately in our full sandbox environment before production activation.',
  },
  {
    q: 'Can I test before going live?',
    a: 'Yes — every merchant receives sandbox API keys and simulated checkout tools to test payment flows, webhooks, and refunds end-to-end.',
  },
  {
    q: 'How are payouts and settlements handled?',
    a: 'GiantPay reconciles incoming payments directly with telecom and bank providers, delivering automated settlement batches to your registered Malawian business bank account.',
  },
];

export default function LandingPage() {
  return (
    <>
      {/* ── Rich Fintech Hero Section ── */}
      <section
        className="relative overflow-hidden text-white"
        style={{
          background: 'linear-gradient(160deg, #061428 0%, #0B2445 32%, #0d2d5e 65%, #071a38 100%)',
        }}
      >
        {/* Background glow orbs */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -top-40 -left-40 h-[600px] w-[600px] rounded-full"
          style={{
            background: 'radial-gradient(circle at 40% 40%, rgba(26,109,204,0.22) 0%, transparent 65%)',
          }}
        />
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -bottom-32 -right-32 h-[550px] w-[550px] rounded-full"
          style={{
            background: 'radial-gradient(circle at 60% 60%, rgba(192,28,40,0.18) 0%, transparent 65%)',
          }}
        />
        <div
          aria-hidden="true"
          className="pointer-events-none absolute top-1/4 right-1/4 h-[400px] w-[400px] rounded-full"
          style={{
            background: 'radial-gradient(circle, rgba(201,162,39,0.1) 0%, transparent 60%)',
          }}
        />

        {/* Waving GP watermark flag */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden"
        >
          <img
            src={MARK_SRC}
            alt=""
            className="animate-flag-wave-slow w-[85vw] max-w-[620px] opacity-[0.08] select-none"
            style={{
              filter: 'drop-shadow(0 20px 60px rgba(26,109,204,0.35))',
            }}
          />
        </div>

        <div className="relative z-10 mx-auto max-w-6xl px-4 pt-16 pb-20 sm:px-6 sm:pt-24 sm:pb-28 text-center">
          {/* Trust Badge */}
          <div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3.5 py-1.5 text-xs font-medium text-white/80 backdrop-blur-md mb-6">
            <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse" />
            <span>Malawi&apos;s Modern Payments Infrastructure</span>
            <span className="hidden sm:inline text-white/30">•</span>
            <span className="hidden sm:inline text-white/60">Bank-Grade 256-Bit SSL</span>
          </div>

          {/* Responsive Heading */}
          <h1 className="mx-auto max-w-4xl text-3xl font-extrabold tracking-tight text-white sm:text-5xl md:text-6xl leading-[1.15]">
            Unified payments.{' '}
            <span
              style={{
                background: 'linear-gradient(135deg, #4da3ff 0%, #c9a227 50%, #ff5263 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              One integration.
            </span>
          </h1>

          {/* Responsive Subheading */}
          <p className="mx-auto mt-5 max-w-2xl text-sm sm:text-base md:text-lg leading-relaxed text-white/70">
            GiantPay helps businesses and digital platforms in Malawi accept and manage configured digital payment
            methods through one secure integration, with clear transaction evidence, developer tools, reconciliation
            and reporting.
          </p>

          {/* Responsive CTA buttons */}
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-3.5 w-full sm:w-auto">
            <Link
              to="/register"
              className="w-full sm:w-auto text-center rounded-xl px-7 py-3 text-sm sm:text-base font-semibold text-white transition-all duration-200 active:scale-[0.98]"
              style={{
                background: 'linear-gradient(135deg, #1a6dcc 0%, #0e4da6 100%)',
                boxShadow: '0 4px 20px rgba(26,109,204,0.4)',
              }}
            >
              Get Started Free
            </Link>
            <Link
              to="/developers"
              className="w-full sm:w-auto text-center rounded-xl px-7 py-3 text-sm sm:text-base font-semibold text-white/90 border border-white/20 bg-white/5 hover:bg-white/10 backdrop-blur-sm transition-all duration-200"
            >
              Explore Developer Tools
            </Link>
          </div>

          {/* Payment method logos */}
          <div className="mt-14 pt-8 border-t border-white/10 flex flex-col items-center gap-4">
            <p className="text-[10px] uppercase font-semibold tracking-[0.2em] text-white/35">
              Designed for local payment integrations
            </p>
            <div className="flex flex-wrap items-center justify-center gap-3" aria-label="Supported payment methods">
              {/* Airtel Money */}
              <div className="flex items-center gap-2 rounded-lg border border-white/12 bg-white/[0.06] px-3 py-2 backdrop-blur-sm">
                <span className="inline-flex h-7 w-14 items-center justify-center rounded bg-white px-1.5">
                  <img src="/brands/airtel-money.svg" alt="Airtel Money" className="h-4 w-auto object-contain" />
                </span>
                <span className="text-xs font-medium text-white/80">Airtel Money</span>
              </div>

              {/* TNM Mpamba */}
              <div className="flex items-center gap-2 rounded-lg border border-white/12 bg-white/[0.06] px-3 py-2 backdrop-blur-sm">
                <span className="inline-flex h-7 w-14 items-center justify-center rounded bg-white px-1.5">
                  <img src="/brands/tnm-mpamba.svg" alt="TNM Mpamba" className="h-4 w-auto object-contain" />
                </span>
                <span className="text-xs font-medium text-white/80">TNM Mpamba</span>
              </div>

              {/* Visa */}
              <div className="flex items-center gap-2 rounded-lg border border-white/12 bg-white/[0.06] px-3 py-2 backdrop-blur-sm">
                <img src="/brands/visa.svg" alt="Visa" className="h-3.5 w-auto object-contain" />
                <span className="text-xs font-medium text-white/80">Visa</span>
              </div>

              {/* Mastercard */}
              <div className="flex items-center gap-2 rounded-lg border border-white/12 bg-white/[0.06] px-3 py-2 backdrop-blur-sm">
                <img src="/brands/mastercard.svg" alt="Mastercard" className="h-4 w-auto object-contain" />
                <span className="text-xs font-medium text-white/80">Mastercard</span>
              </div>

              {/* National Switch */}
              <div className="flex items-center gap-2 rounded-lg border border-white/12 bg-white/[0.06] px-3 py-2 backdrop-blur-sm">
                <svg className="h-4 w-4 text-blue-300 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75} aria-hidden="true">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                </svg>
                <span className="text-xs font-medium text-white/80">National Switch</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── How GiantPay Works ── */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="text-center max-w-2xl mx-auto">
          <p className="text-xs font-bold uppercase tracking-widest text-blue-600">Simple 3-step setup</p>
          <h2 className="mt-2 text-2xl sm:text-3xl font-bold tracking-tight text-[var(--color-navy-900)]">
            How GiantPay works
          </h2>
          <p className="mt-2 text-sm text-[var(--color-neutral-600)]">
            From registration to live settlements in just three straightforward steps.
          </p>
        </div>

        <ol className="mx-auto mt-12 grid max-w-4xl gap-6 sm:grid-cols-3">
          {[
            {
              step: '1',
              title: 'Register & verify',
              body: 'Submit your business profile and KYC/KYB registration details for rapid compliance review.',
            },
            {
              step: '2',
              title: 'Integrate & test',
              body: 'Build against our complete sandbox using hosted payment links or REST API keys.',
            },
            {
              step: '3',
              title: 'Go live',
              body: 'Switch to production credentials and receive automated payouts directly to your bank account.',
            },
          ].map((item) => (
            <li
              key={item.step}
              className="group relative rounded-2xl border border-[var(--color-neutral-200)] bg-white p-6 text-center shadow-sm transition-all duration-200 hover:-translate-y-1 hover:shadow-md"
            >
              <span className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-base font-bold text-blue-600 group-hover:bg-blue-600 group-hover:text-white transition-colors duration-200">
                {item.step}
              </span>
              <h3 className="mt-4 text-base font-semibold text-[var(--color-navy-900)]">{item.title}</h3>
              <p className="mt-2 text-xs sm:text-sm leading-relaxed text-[var(--color-neutral-600)]">{item.body}</p>
            </li>
          ))}
        </ol>
      </section>

      {/* ── Built for Merchants and Developers ── */}
      <section className="bg-[var(--color-neutral-50)] py-16 sm:py-20 border-y border-[var(--color-neutral-200)]">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="text-center max-w-2xl mx-auto">
            <p className="text-xs font-bold uppercase tracking-widest text-blue-600">Enterprise Ready</p>
            <h2 className="mt-2 text-2xl sm:text-3xl font-bold tracking-tight text-[var(--color-navy-900)]">
              Built for merchants and developers
            </h2>
            <p className="mt-2 text-sm text-[var(--color-neutral-600)]">
              Engineered with reliability, financial auditability, and ease of integration at its core.
            </p>
          </div>

          <div className="mt-12 grid gap-5 sm:grid-cols-2">
            {BENEFITS.map((b) => (
              <div
                key={b.title}
                className="flex items-start gap-4 rounded-2xl border border-[var(--color-neutral-200)] bg-white p-6 shadow-sm transition-all duration-200 hover:shadow-md"
              >
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-blue-50">
                  {b.icon}
                </div>
                <div>
                  <h3 className="text-base font-semibold text-[var(--color-navy-900)]">{b.title}</h3>
                  <p className="mt-1.5 text-xs sm:text-sm leading-relaxed text-[var(--color-neutral-600)]">{b.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Developer Experience Section ── */}
      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="rounded-3xl border border-[var(--color-neutral-200)] bg-[var(--color-navy-950)] text-white p-6 sm:p-10 lg:p-12 overflow-hidden relative">
          {/* Subtle glow */}
          <div
            aria-hidden="true"
            className="pointer-events-none absolute top-0 right-0 h-[350px] w-[350px] rounded-full"
            style={{
              background: 'radial-gradient(circle, rgba(26,109,204,0.2) 0%, transparent 70%)',
            }}
          />

          <div className="relative z-10 grid gap-8 lg:grid-cols-2 lg:items-center">
            <div>
              <div className="inline-flex items-center gap-2 rounded-lg bg-blue-500/10 border border-blue-400/20 px-3 py-1 text-xs font-semibold text-blue-300 mb-4">
                <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                </svg>
                Developer-First API
              </div>
              <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
                Clean, predictable APIs and webhooks
              </h2>
              <p className="mt-4 text-sm sm:text-base leading-relaxed text-white/70">
                Sandbox and production API keys, webhooks with delivery history, idempotent requests, and documentation with
                cURL, JavaScript/TypeScript and PHP examples — all built around the same trusted-status model the hosted
                checkout uses.
              </p>
              <div className="mt-6 flex flex-wrap gap-3">
                <Link
                  to="/developers"
                  className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow hover:bg-blue-500 transition-colors"
                >
                  View Developer Docs
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                  </svg>
                </Link>
                <Link
                  to="/register"
                  className="inline-flex items-center rounded-xl border border-white/20 bg-white/5 px-5 py-2.5 text-sm font-semibold text-white hover:bg-white/10 transition-colors"
                >
                  Get API Keys
                </Link>
              </div>
            </div>

            {/* Code / API Snippet Preview */}
            <div className="rounded-2xl border border-white/10 bg-black/40 p-4 sm:p-5 backdrop-blur-md overflow-x-auto">
              <div className="flex items-center justify-between pb-3 border-b border-white/10 text-xs text-white/50">
                <div className="flex items-center gap-1.5">
                  <span className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
                  <span className="h-2.5 w-2.5 rounded-full bg-amber-500/80" />
                  <span className="h-2.5 w-2.5 rounded-full bg-emerald-500/80" />
                  <span className="ml-2 font-mono text-[11px] text-white/60">POST /v1/checkout/sessions</span>
                </div>
                <span className="font-mono text-[10px] text-emerald-400">201 Created</span>
              </div>
              <pre className="mt-3 font-mono text-xs text-blue-200 leading-relaxed overflow-x-auto">
{`{
  "reference": "gp_req_91b7e4c2",
  "amount": 2500000,
  "currency": "MWK",
  "channels": ["AIRTEL_MONEY", "TNM_MPAMBA", "CARD"],
  "status": "INITIATED",
  "checkout_url": "https://pay.giantpay.mw/checkout/tok_..."
}`}
              </pre>
            </div>
          </div>
        </div>
      </section>

      {/* ── Frequently Asked Questions ── */}
      <section className="border-t border-[var(--color-neutral-200)] py-16 sm:py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <div className="text-center mb-10">
            <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-[var(--color-navy-900)]">
              Frequently asked questions
            </h2>
            <p className="mt-2 text-sm text-[var(--color-neutral-600)]">
              Everything you need to know about payments, regulatory alignment, and testing.
            </p>
          </div>

          <dl className="flex flex-col gap-4">
            {FAQS.map((faq) => (
              <div
                key={faq.q}
                className="rounded-2xl border border-[var(--color-neutral-200)] bg-white p-5 sm:p-6 shadow-sm"
              >
                <dt className="font-semibold text-sm sm:text-base text-[var(--color-navy-900)]">{faq.q}</dt>
                <dd className="mt-2 text-xs sm:text-sm leading-relaxed text-[var(--color-neutral-600)]">{faq.a}</dd>
              </div>
            ))}
          </dl>
        </div>
      </section>
    </>
  );
}
