import 'dotenv/config';
import { randomUUID } from 'node:crypto';
import { readFile,readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import pg from 'pg';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { MemoryRateLimitStore } from '../src/rateLimit.js';
import { tokenHash } from '../src/security.js';
import { requireSafeTestDatabase } from './integrationGuard.js';

const url=process.env.TEST_DATABASE_URL?requireSafeTestDatabase(process.env.TEST_DATABASE_URL,process.env.ALLOW_REMOTE_TEST_DATABASE==='true').toString():undefined,suite=url?describe:describe.skip,schema=`disputes_test_${randomUUID().replaceAll('-','')}`;
let admin:pg.Pool,db:pg.Pool,app:Awaited<ReturnType<typeof buildApp>>,disputeId:string;
const human=(token:string)=>({cookie:`giantpay_session=${token}; giantpay_csrf=c`,origin:'http://127.0.0.1:5173','x-csrf-token':'c'}),idem=(token:string,key:string)=>({...human(token),'idempotency-key':key});
const create=(key='create-dispute',overrides:Record<string,unknown>={})=>app.inject({method:'POST',url:'/v1/platform/disputes',headers:idem('creator-token',key),payload:{paymentId:'pay1',source:'SANDBOX',reasonCategory:'FRAUDULENT',amountMinor:400,currency:'MWK',summary:'Fictional sandbox customer challenge',...overrides}});

suite('sandbox disputes and chargebacks',()=>{
 beforeAll(async()=>{admin=new pg.Pool({connectionString:url!});await admin.query(`CREATE SCHEMA ${schema}`);db=new pg.Pool({connectionString:url!,options:`-c search_path=${schema}`});for(const name of (await readdir(resolve('migrations'))).filter(x=>x.endsWith('.sql')).sort())await db.query(await readFile(resolve('migrations',name),'utf8'));await db.query(`
 INSERT INTO merchants(id,name) VALUES('m1','Fictional One'),('m2','Fictional Two');
 INSERT INTO users(id,merchant_id,name,email,normalized_email,password_hash,role,permissions,status) VALUES
 ('owner1','m1','Owner One','owner1@example.invalid','owner1@example.invalid','x','OWNER',ARRAY['disputes.read','disputes.respond','disputes.evidence.create'],'ACTIVE'),
 ('owner2','m2','Owner Two','owner2@example.invalid','owner2@example.invalid','x','OWNER',ARRAY['disputes.read','disputes.respond','disputes.evidence.create'],'ACTIVE'),
 ('creator',NULL,'Creator','creator@example.invalid','creator@example.invalid','x','PLATFORM_ADMIN',ARRAY['platform.disputes.read','platform.disputes.investigate','platform.disputes.request_information','platform.disputes.decide','platform.disputes.assign','platform.disputes.reopen'],'ACTIVE'),
 ('proposer',NULL,'Proposer','proposer@example.invalid','proposer@example.invalid','x','PLATFORM_ADMIN',ARRAY['platform.disputes.read','platform.disputes.investigate','platform.disputes.decide'],'ACTIVE'),
 ('checker',NULL,'Checker','checker@example.invalid','checker@example.invalid','x','PLATFORM_ADMIN',ARRAY['platform.disputes.read','platform.disputes.investigate','platform.disputes.decide'],'ACTIVE'),
 ('limited',NULL,'Limited','limited@example.invalid','limited@example.invalid','x','PLATFORM_ADMIN',ARRAY[]::text[],'ACTIVE'),
 ('disabled',NULL,'Disabled','disabled@example.invalid','disabled@example.invalid','x','PLATFORM_ADMIN',ARRAY['platform.disputes.read'],'SUSPENDED');
 INSERT INTO payments(id,merchant_id,reference,status,channel,provider_name,gross_minor,currency,customer) VALUES('pay1','m1','PAY-DSP-1','SUCCEEDED','SANDBOX','sandbox',1000,'MWK','{"email":"secret@example.invalid"}'),('pay2','m2','PAY-DSP-2','SUCCEEDED','SANDBOX','sandbox',1000,'MWK','{}'),('failed','m1','PAY-DSP-F','FAILED','SANDBOX','sandbox',1000,'MWK','{}');
 `);for(const [t,u] of [['owner1-token','owner1'],['owner2-token','owner2'],['creator-token','creator'],['proposer-token','proposer'],['checker-token','checker'],['limited-token','limited'],['disabled-token','disabled']] as const)await db.query('INSERT INTO sessions(token_hash,user_id,expires_at,absolute_expires_at,last_seen_at) VALUES($1,$2,now()+interval \'1 hour\',now()+interval \'2 hours\',now())',[tokenHash(t),u]);app=await buildApp(loadConfig({NODE_ENV:'test',DATABASE_URL:url!,PASSWORD_PEPPER:'p'.repeat(32),COOKIE_SECRET:'c'.repeat(32),FRONTEND_ORIGIN:'http://127.0.0.1:5173',PAYMENT_PROVIDER:'sandbox',SANDBOX_WEBHOOK_SECRET:'w'.repeat(32)}),db,undefined,undefined,new MemoryRateLimitStore());});
 afterAll(async()=>{await app?.close();await db?.end();await admin?.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin?.end();});

 it('enforces authentication, permissions, authority separation, and disabled-user denial',async()=>{expect((await app.inject({url:'/v1/disputes'})).statusCode).toBe(401);expect((await app.inject({url:'/v1/platform/disputes'})).statusCode).toBe(401);expect((await app.inject({url:'/v1/platform/disputes',headers:human('owner1-token')})).statusCode).toBe(403);expect((await app.inject({url:'/v1/disputes',headers:human('creator-token')})).statusCode).toBe(403);expect((await app.inject({url:'/v1/platform/disputes',headers:human('limited-token')})).statusCode).toBe(403);expect((await app.inject({url:'/v1/platform/disputes',headers:human('disabled-token')})).statusCode).toBe(401);expect((await app.inject({url:'/v1/platform/disputes',headers:{authorization:'Bearer fake'}})).statusCode).toBe(403);});
 it('validates payment eligibility, currency, amounts, provider claims, and remaining disputable value',async()=>{expect((await create('bad-state',{paymentId:'failed'})).statusCode).toBe(422);expect((await create('bad-currency',{currency:'USD'})).statusCode).toBe(422);expect((await create('bad-zero',{amountMinor:0})).statusCode).toBe(400);expect((await create('bad-provider',{source:'PROVIDER_REPORTED'})).statusCode).toBe(422);expect((await create('too-large',{amountMinor:1001})).statusCode).toBe(422);});
 it('creates atomically, replays the original response, conflicts on changed input, and exposes no customer secrets',async()=>{const a=await create(),b=await create();expect(a.statusCode,a.body).toBe(201);expect(b.json()).toEqual(a.json());disputeId=a.json().id;expect((await create('create-dispute',{amountMinor:401})).statusCode).toBe(409);expect(a.json()).toMatchObject({source:'SANDBOX',sandboxOnly:true});expect(a.body).not.toContain('secret@example.invalid');expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE resource_id=$1 AND action='DISPUTE_CREATED'`,[disputeId])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM outbox_events WHERE aggregate_id=$1`,[disputeId])).rows[0].count)).toBe(1);expect((await create('partial-overflow',{amountMinor:601})).statusCode).toBe(422);});
 it('isolates tenant lists/details and keeps internal notes physically private',async()=>{expect((await app.inject({url:`/v1/disputes/${disputeId}`,headers:human('owner2-token')})).statusCode).toBe(404);expect((await app.inject({url:'/v1/disputes',headers:human('owner2-token')})).json().data).toHaveLength(0);const note=await app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/internal-notes`,headers:idem('creator-token','private-note'),payload:{body:'Private operational investigation note'}});expect(note.statusCode,note.body).toBe(201);const merchant=await app.inject({url:`/v1/disputes/${disputeId}`,headers:human('owner1-token')});expect(merchant.body).not.toContain('Private operational investigation note');expect(merchant.body).not.toContain('internalNotes');expect((await app.inject({url:`/v1/platform/disputes/${disputeId}`,headers:human('creator-token')})).body).toContain('Private operational investigation note');});
 it('records idempotent merchant responses and metadata-only evidence',async()=>{const response=()=>app.inject({method:'POST',url:`/v1/disputes/${disputeId}/responses`,headers:idem('owner1-token','merchant-response'),payload:{body:'The fictional sandbox order was delivered.'}}),a=await response(),b=await response();expect(a.statusCode,a.body).toBe(201);expect(b.json()).toEqual(a.json());const evidence=()=>app.inject({method:'POST',url:`/v1/disputes/${disputeId}/evidence`,headers:idem('owner1-token','merchant-evidence'),payload:{evidenceType:'DELIVERY_RECEIPT',description:'Fictional delivery receipt metadata',originalFilename:'receipt.pdf',mimeType:'application/pdf',fileSize:100,checksumSha256:'a'.repeat(64)}}),e1=await evidence(),e2=await evidence();expect(e1.statusCode,e1.body).toBe(201);expect(e2.json()).toEqual(e1.json());expect(e1.json()).toMatchObject({uploadAccepted:false,message:'Sandbox metadata recorded; no file was uploaded.'});expect(e1.body).not.toMatch(/bucket|filesystem|credential|encryption/i);});
 it('uses expected-state locking for information requests and concurrent assignments',async()=>{
  const info=await app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/request-information`,headers:idem('creator-token','need-information'),payload:{reason:'Please provide more fictional documentation',expectedStatus:'OPEN',expectedVersion:1}});expect(info.statusCode,info.body).toBe(200);
  await app.inject({method:'POST',url:`/v1/disputes/${disputeId}/responses`,headers:idem('owner1-token','requested-response'),payload:{body:'Additional fictional information supplied.'}});
  const responded=(await db.query('SELECT version FROM disputes WHERE id=$1',[disputeId])).rows[0],assign=(key:string,staffId:string)=>app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/assign`,headers:idem('creator-token',key),payload:{staffId,expectedAssigneeId:null,expectedVersion:responded.version,reason:'Concurrent investigation assignment'}}),results=await Promise.all([assign('assign-one','checker'),assign('assign-two','checker')]);
  expect(results.filter(x=>x.statusCode===200),results.map(x=>x.body).join('\n')).toHaveLength(1);expect(results.filter(x=>x.statusCode===409)).toHaveLength(1);
  const current=(await db.query('SELECT assigned_to,version FROM disputes WHERE id=$1',[disputeId])).rows[0],disabled=await app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/assign`,headers:idem('creator-token','assign-disabled'),payload:{staffId:'disabled',expectedAssigneeId:current.assigned_to,expectedVersion:current.version,reason:'Reject disabled assignee'}});expect(disabled.statusCode,disabled.body).toBe(422);
 });
 it('enforces lifecycle and maker-checker with one durable pending financial instruction and no payout',async()=>{
  await db.query(`INSERT INTO users(id,merchant_id,name,email,normalized_email,password_hash,role,permissions,status) VALUES('reviewer',NULL,'Independent Reviewer','reviewer@example.invalid','reviewer@example.invalid','x','PLATFORM_ADMIN',ARRAY['platform.disputes.read','platform.disputes.decide'],'ACTIVE')`);
  await db.query(`INSERT INTO sessions(token_hash,user_id,expires_at,absolute_expires_at,last_seen_at) VALUES($1,'reviewer',now()+interval '1 hour',now()+interval '2 hours',now())`,[tokenHash('reviewer-token')]);
  let d=(await db.query('SELECT * FROM disputes WHERE id=$1',[disputeId])).rows[0];const review=await app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/status`,headers:idem('creator-token','under-review'),payload:{status:'UNDER_REVIEW',expectedStatus:d.status,expectedVersion:d.version,reason:'Begin fictional sandbox review'}});expect(review.statusCode,review.body).toBe(200);d=review.json();
  const propose=await app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/decisions`,headers:idem('proposer-token','propose-loss'),payload:{action:'PROPOSE',outcome:'LOST',reason:'Fictional evidence supports sandbox loss',evidenceIds:[],expectedStatus:'UNDER_REVIEW',expectedVersion:d.version}});expect(propose.statusCode,propose.body).toBe(201);
  const self=await app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/decisions`,headers:idem('proposer-token','self-check'),payload:{action:'APPROVE',decisionId:propose.json().id,reason:'Self approval is forbidden',expectedStatus:'UNDER_REVIEW',expectedVersion:d.version}});expect(self.statusCode).toBe(409);
  const approve=()=>app.inject({method:'POST',url:`/v1/platform/disputes/${disputeId}/decisions`,headers:idem('reviewer-token','approve-loss'),payload:{action:'APPROVE',decisionId:propose.json().id,reason:'Independent fictional sandbox review',expectedStatus:'UNDER_REVIEW',expectedVersion:d.version}}),approved=await approve();expect(approved.statusCode,approved.body).toBe(200);expect(approved.json()).toMatchObject({status:'LOST',financialEffect:'PENDING',providerAction:false,payout:false});expect((await approve()).json()).toEqual(approved.json());
  expect(Number((await db.query('SELECT count(*) FROM dispute_financial_effects WHERE dispute_id=$1',[disputeId])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM journal_entries WHERE source_id=$1`,[disputeId])).rows[0].count)).toBe(0);
 });
 it('enforces all histories as append-only even for zero-row statements',async()=>{for(const table of ['dispute_public_responses','dispute_evidence','dispute_internal_notes','dispute_status_history','dispute_assignment_history','dispute_decision_history','dispute_financial_effects']){await expect(db.query(`UPDATE ${table} SET id=id WHERE id='missing'`),table).rejects.toThrow(/append-only/i);await expect(db.query(`DELETE FROM ${table} WHERE id='missing'`),table).rejects.toThrow(/append-only/i);}});
 it('validates deterministic cursors, page sizes, and date ranges',async()=>{expect((await app.inject({url:'/v1/platform/disputes?limit=101',headers:human('creator-token')})).statusCode).toBe(422);expect((await app.inject({url:'/v1/platform/disputes?cursor=invalid',headers:human('creator-token')})).statusCode).toBe(422);expect((await app.inject({url:'/v1/platform/disputes?from=2026-09-16T00:00:00.000Z&to=2026-09-15T00:00:00.000Z',headers:human('creator-token')})).statusCode).toBe(422);const page=await app.inject({url:'/v1/platform/disputes?limit=1',headers:human('creator-token')});expect(page.statusCode).toBe(200);});
});
