import 'dotenv/config';
import { randomUUID } from 'node:crypto';
import { readFile,readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import pg from 'pg';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { createNotificationFromEvent,NotificationDeliveryWorker,retryDelaySeconds } from '../src/notifications/service.js';
import { MemoryRateLimitStore } from '../src/rateLimit.js';
import { tokenHash } from '../src/security.js';
import { requireSafeTestDatabase } from './integrationGuard.js';

const databaseUrl=process.env.TEST_DATABASE_URL?requireSafeTestDatabase(process.env.TEST_DATABASE_URL,process.env.ALLOW_REMOTE_TEST_DATABASE==='true').toString():undefined,suite=databaseUrl?describe:describe.skip,schema=`notification_tx_${randomUUID().replaceAll('-','')}`;
let admin:pg.Pool,db:pg.Pool,app:Awaited<ReturnType<typeof buildApp>>;
const session=(token:string)=>({cookie:`giantpay_session=${token}; giantpay_csrf=c`,origin:'http://127.0.0.1:5173','x-csrf-token':'c'}),idem=(token:string,key:string)=>({...session(token),'idempotency-key':key});
const tables=['notifications','notification_recipients','notification_preferences','notification_event_receipts','notification_delivery_jobs','notification_delivery_attempts','notification_read_history','audit_events','outbox_events','notification_idempotency'] as const;
const snapshot=async()=>Object.fromEntries(await Promise.all(tables.map(async table=>[table,Number((await db.query(`SELECT count(*) FROM ${table}`)).rows[0].count)])));
const expectUnchanged=async(before:Record<string,number>)=>expect(await snapshot()).toEqual(before);
const clearFault=async()=>{await db.query('DROP TRIGGER IF EXISTS phase9_injected_failure ON audit_events;DROP TRIGGER IF EXISTS phase9_injected_failure ON outbox_events;DROP TRIGGER IF EXISTS phase9_injected_failure ON notification_delivery_jobs;DROP FUNCTION IF EXISTS phase9_injected_failure()')};
const fault=async(table:'audit_events'|'outbox_events'|'notification_delivery_jobs',timing:'INSERT'|'UPDATE',condition:string)=>{await clearFault();await db.query(`CREATE FUNCTION phase9_injected_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'phase9 injected failure'; END $$;CREATE TRIGGER phase9_injected_failure BEFORE ${timing} ON ${table} FOR EACH ROW WHEN (${condition}) EXECUTE FUNCTION phase9_injected_failure()`)};
const directNotification=async(user='u1')=>{const nid=`ntf_${randomUUID().replaceAll('-','')}`;await db.query(`INSERT INTO notifications(id,authority,merchant_id,recipient_user_id,category,template_key,template_version,title,body,channel,delivery_state,deduplication_key) VALUES($1,'MERCHANT','m1',$2,'SYSTEM','generic.merchant.event',1,'Safe title','Safe body','IN_APP','DELIVERED',$3)`,[nid,user,`dedupe-${nid}`]);await db.query('INSERT INTO notification_recipients(notification_id,recipient_user_id,merchant_id) VALUES($1,$2,\'m1\')',[nid,user]);return nid;};
const job=async(state='PENDING',attempt=0,max=3,channel='IN_APP',leaseOwner:string|null=null,leaseExpiry:string|null=null)=>{const nid=await directNotification(),jid=`ndj_${randomUUID().replaceAll('-','')}`;await db.query(`INSERT INTO notification_delivery_jobs(id,notification_id,channel,state,attempt_count,max_attempts,available_at,lease_owner,lease_expires_at) VALUES($1,$2,$3,$4,$5,$6,now()-interval '1 second',$7,$8)`,[jid,nid,channel,state,attempt,max,leaseOwner,leaseExpiry]);return {nid,jid};};

suite('Phase 9 transaction rollback and delivery concurrency',()=>{
 beforeAll(async()=>{admin=new pg.Pool({connectionString:databaseUrl!});await admin.query(`CREATE SCHEMA ${schema}`);db=new pg.Pool({connectionString:databaseUrl!,options:`-c search_path=${schema}`});for(const name of (await readdir(resolve('migrations'))).filter(x=>x.endsWith('.sql')).sort())await db.query(await readFile(resolve('migrations',name),'utf8'));await db.query(`INSERT INTO merchants(id,name) VALUES('m1','Rollback Merchant')`);await db.query(`INSERT INTO users(id,merchant_id,name,email,normalized_email,password_hash,role,permissions,status) VALUES('u1','m1','User One','one@example.invalid','one@example.invalid','x','OWNER',ARRAY['notifications.read','notifications.mark_read','notifications.manage_preferences'],'ACTIVE'),('staff',NULL,'Staff','staff@example.invalid','staff@example.invalid','x','PLATFORM_ADMIN',ARRAY['platform.notifications.delivery.read','platform.notifications.delivery.retry'],'ACTIVE')`);await db.query(`INSERT INTO sessions(token_hash,user_id,expires_at,absolute_expires_at,last_seen_at) VALUES($1,'u1',now()+interval '1 hour',now()+interval '2 hours',now()),($2,'staff',now()+interval '1 hour',now()+interval '2 hours',now())`,[tokenHash('u1-token'),tokenHash('staff-token')]);app=await buildApp(loadConfig({NODE_ENV:'test',DATABASE_URL:databaseUrl!,PASSWORD_PEPPER:'p'.repeat(32),COOKIE_SECRET:'c'.repeat(32),FRONTEND_ORIGIN:'http://127.0.0.1:5173',PAYMENT_PROVIDER:'sandbox',SANDBOX_WEBHOOK_SECRET:'w'.repeat(32)}),db,undefined,undefined,new MemoryRateLimitStore());});
 afterAll(async()=>{await clearFault().catch(()=>undefined);await app?.close();await db?.end();await admin?.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin?.end();});

 it('rolls back notification creation from an outbox event after recipient and receipt writes',async()=>{const before=await snapshot();await fault('audit_events','INSERT',`NEW.action='NOTIFICATION_CREATED'`);await expect(createNotificationFromEvent(db,{id:'rollback-create',eventType:'support.status.changed',aggregateType:'support_case',aggregateId:'case-rollback',payload:{merchantId:'m1'}},'u1')).rejects.toThrow(/injected failure/);await clearFault();await expectUnchanged(before);});
 it('rolls back marking one notification read after history and audit writes',async()=>{const nid=await directNotification(),before=await snapshot();await fault('outbox_events','INSERT',`NEW.event_type='notification.read'`);const response=await app.inject({method:'POST',url:`/v1/notifications/${nid}/read`,headers:idem('u1-token','rollback-mark-one'),payload:{}});expect(response.statusCode).toBe(500);await clearFault();await expectUnchanged(before);});
 it('rolls back marking all notifications read after multiple history and audit writes',async()=>{await directNotification();await directNotification();const before=await snapshot();await fault('outbox_events','INSERT',`NEW.event_type='notifications.read.all'`);const response=await app.inject({method:'POST',url:'/v1/notifications/read-all',headers:idem('u1-token','rollback-mark-all'),payload:{}});expect(response.statusCode).toBe(500);await clearFault();await expectUnchanged(before);});
 it('rolls back notification-preference updates after the preference and audit writes',async()=>{const before=await snapshot();await fault('outbox_events','INSERT',`NEW.event_type='notification.preferences.updated'`);const response=await app.inject({method:'PATCH',url:'/v1/notifications/preferences',headers:idem('u1-token','rollback-preference'),payload:{category:'PAYMENT',channel:'EMAIL',enabled:false,expectedVersion:0}});expect(response.statusCode).toBe(500);await clearFault();await expectUnchanged(before);});
 it('rolls back worker job claiming after the lease update',async()=>{const {jid}=await job(),before=await snapshot();await fault('audit_events','INSERT',`NEW.action='NOTIFICATION_DELIVERY_CLAIMED'`);await expect(new NotificationDeliveryWorker(db).claim('rollback-claim')).rejects.toThrow(/injected failure/);await clearFault();await expectUnchanged(before);expect((await db.query('SELECT state,attempt_count,lease_owner FROM notification_delivery_jobs WHERE id=$1',[jid])).rows[0]).toMatchObject({state:'PENDING',attempt_count:0,lease_owner:null});});
 it('rolls back delivery-attempt recording when the subsequent job update fails',async()=>{const {jid}=await job('CLAIMED',1,3,'IN_APP','worker-a','2999-01-01'),before=await snapshot();await fault('notification_delivery_jobs','UPDATE',`NEW.state='FAILED_RETRYABLE'`);await expect(new NotificationDeliveryWorker(db).finishFailure(jid,'worker-a','SANDBOX_FAILURE')).rejects.toThrow(/injected failure/);await clearFault();await expectUnchanged(before);expect((await db.query('SELECT state,lease_owner FROM notification_delivery_jobs WHERE id=$1',[jid])).rows[0]).toMatchObject({state:'CLAIMED',lease_owner:'worker-a'});});
 it('rolls back expired-lease recovery after the reclaimed lease write',async()=>{const {jid}=await job('DEFERRED',1,3,'IN_APP','expired-worker','2000-01-01'),before=await snapshot();await fault('audit_events','INSERT',`NEW.action='NOTIFICATION_DELIVERY_CLAIMED'`);await expect(new NotificationDeliveryWorker(db).claim('recovery-worker')).rejects.toThrow(/injected failure/);await clearFault();await expectUnchanged(before);expect((await db.query('SELECT state,lease_owner FROM notification_delivery_jobs WHERE id=$1',[jid])).rows[0]).toMatchObject({state:'DEFERRED',lease_owner:'expired-worker'});});
 it('rolls back manual delivery retry after the job and audit writes',async()=>{const {jid}=await job('FAILED_RETRYABLE',1),before=await snapshot();await fault('outbox_events','INSERT',`NEW.event_type='notification.delivery.retry.requested'`);const response=await app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${jid}/retry`,headers:idem('staff-token','rollback-manual-retry'),payload:{expectedState:'FAILED_RETRYABLE',reason:'Injected rollback verification'}});expect(response.statusCode).toBe(500);await clearFault();await expectUnchanged(before);expect((await db.query('SELECT state FROM notification_delivery_jobs WHERE id=$1',[jid])).rows[0].state).toBe('FAILED_RETRYABLE');});

 it('uses deterministic exponential retry backoff and becomes terminal at the configured maximum',async()=>{expect([1,2,3,20].map(retryDelaySeconds)).toEqual([2,4,8,3600]);const {jid}=await job('PENDING',0,3),worker=new NotificationDeliveryWorker(db);for(let attempt=1;attempt<=3;attempt++){const claimed=await worker.claim(`worker-${attempt}`,100),row=claimed.find(x=>x.id===jid);expect(row?.attempt_count).toBe(attempt);const result=await worker.finishFailure(jid,`worker-${attempt}`,'RETRYABLE');expect(result).toEqual(attempt===3?{state:'FAILED_TERMINAL',delaySeconds:null}:{state:'FAILED_RETRYABLE',delaySeconds:2**attempt});if(attempt<3)await db.query(`UPDATE notification_delivery_jobs SET available_at=now()-interval '1 second' WHERE id=$1`,[jid]);}expect((await db.query('SELECT state,attempt_count FROM notification_delivery_jobs WHERE id=$1',[jid])).rows[0]).toMatchObject({state:'FAILED_TERMINAL',attempt_count:3});expect((await worker.claim('never-reclaim',100)).some(x=>x.id===jid)).toBe(false);expect(Number((await db.query('SELECT count(*) FROM notification_delivery_attempts WHERE job_id=$1',[jid])).rows[0].count)).toBe(3);});
 it('reclaims an expired lease exactly once while an active lease cannot be stolen',async()=>{const expired=await job('DEFERRED',1,3,'IN_APP','old','2000-01-01'),active=await job('DEFERRED',1,3,'IN_APP','live','2999-01-01'),worker=new NotificationDeliveryWorker(db),claims=(await Promise.all([worker.claim('a',100),worker.claim('b',100)])).flat();expect(claims.filter(x=>x.id===expired.jid)).toHaveLength(1);expect(claims.some(x=>x.id===active.jid)).toBe(false);});
 it('allows exactly one worker to record an attempt and never creates duplicate attempt numbers',async()=>{const {jid}=await job(),worker=new NotificationDeliveryWorker(db);await worker.claim('attempt-worker',100);const results=await Promise.allSettled([worker.finishFailure(jid,'attempt-worker','FAIL'),worker.finishFailure(jid,'attempt-worker','FAIL')]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);expect(Number((await db.query('SELECT count(*) FROM notification_delivery_attempts WHERE job_id=$1 AND attempt_number=1',[jid])).rows[0].count)).toBe(1);});
 it('replays identical manual retries and creates one audit, outbox, and idempotency effect',async()=>{const {jid}=await job('FAILED_RETRYABLE',1),call=()=>app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${jid}/retry`,headers:idem('staff-token','manual-retry-replay'),payload:{expectedState:'FAILED_RETRYABLE',reason:'Safe operational retry'}}),a=await call(),b=await call();expect(a.statusCode,a.body).toBe(200);expect(b.json()).toEqual(a.json());expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE action='NOTIFICATION_DELIVERY_RETRY_REQUESTED' AND metadata->>'deliveryId'=$1`,[jid])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM outbox_events WHERE event_type='notification.delivery.retry.requested' AND payload->>'deliveryId'=$1`,[jid])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM notification_idempotency WHERE operation='delivery.retry' AND resource_id=$1`,[jid])).rows[0].count)).toBe(1);});
 it('returns IDEMPOTENCY_CONFLICT when a manual-retry key is reused with changed input',async()=>{const {jid}=await job('FAILED_RETRYABLE',1),headers=idem('staff-token','manual-retry-conflict'),first=await app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${jid}/retry`,headers,payload:{expectedState:'FAILED_RETRYABLE',reason:'First safe reason'}});expect(first.statusCode).toBe(200);const changed=await app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${jid}/retry`,headers,payload:{expectedState:'FAILED_RETRYABLE',reason:'Changed safe reason'}});expect(changed.statusCode).toBe(409);expect(changed.json().error.code).toBe('IDEMPOTENCY_CONFLICT');});
 it('serializes two concurrent manual retries with exactly one winner',async()=>{const {jid}=await job('FAILED_RETRYABLE',1),call=(key:string)=>app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${jid}/retry`,headers:idem('staff-token',key),payload:{expectedState:'FAILED_RETRYABLE',reason:'Concurrent retry request'}}),responses=await Promise.all([call('concurrent-retry-a'),call('concurrent-retry-b')]);expect(responses.filter(x=>x.statusCode===200)).toHaveLength(1);expect(responses.filter(x=>x.statusCode===409)).toHaveLength(1);expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE action='NOTIFICATION_DELIVERY_RETRY_REQUESTED' AND metadata->>'deliveryId'=$1`,[jid])).rows[0].count)).toBe(1);});
 it('never lets manual retry bypass disabled email or SMS providers',async()=>{for(const channel of ['EMAIL','SMS']){const {jid}=await job('DISABLED',1,3,channel);const response=await app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${jid}/retry`,headers:idem('staff-token',`disabled-${channel.toLowerCase()}`),payload:{expectedState:'DISABLED',reason:'Provider remains unavailable'}});expect(response.statusCode).toBe(409);expect(response.json().error.code).toBe('NOTIFICATION_PROVIDER_DISABLED');expect((await db.query('SELECT state FROM notification_delivery_jobs WHERE id=$1',[jid])).rows[0].state).toBe('DISABLED');}});
});
