import 'dotenv/config';
import { randomUUID } from 'node:crypto';
import { readFile,readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import pg from 'pg';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { MemoryRateLimitStore } from '../src/rateLimit.js';
import { createNotificationFromEvent,NotificationDeliveryWorker,renderTemplate } from '../src/notifications/service.js';
import { tokenHash } from '../src/security.js';
import { requireSafeTestDatabase } from './integrationGuard.js';

const url=process.env.TEST_DATABASE_URL?requireSafeTestDatabase(process.env.TEST_DATABASE_URL,process.env.ALLOW_REMOTE_TEST_DATABASE==='true').toString():undefined,suite=url?describe:describe.skip,schema=`notifications_test_${randomUUID().replaceAll('-','')}`;
let admin:pg.Pool,db:pg.Pool,app:Awaited<ReturnType<typeof buildApp>>,notificationId:string;
const human=(token:string)=>({cookie:`giantpay_session=${token}; giantpay_csrf=c`,origin:'http://127.0.0.1:5173','x-csrf-token':'c'}),idem=(token:string,k:string)=>({...human(token),'idempotency-key':k});
const event=(id:string)=>({id,eventType:'support.status.changed',aggregateType:'support_case',aggregateId:`case-${id}`,payload:{merchantId:'m1',internalNote:'must not render',email:'secret@example.invalid'}});

suite('Phase 9 notifications and communications',()=>{
 beforeAll(async()=>{admin=new pg.Pool({connectionString:url!});await admin.query(`CREATE SCHEMA ${schema}`);db=new pg.Pool({connectionString:url!,options:`-c search_path=${schema}`});for(const name of (await readdir(resolve('migrations'))).filter(x=>x.endsWith('.sql')).sort())await db.query(await readFile(resolve('migrations',name),'utf8'));await db.query(`
 INSERT INTO merchants(id,name) VALUES('m1','Fictional Merchant One'),('m2','Fictional Merchant Two');
 INSERT INTO users(id,merchant_id,name,email,normalized_email,password_hash,role,permissions,status) VALUES
 ('u1','m1','User One','one@example.invalid','one@example.invalid','x','OWNER',ARRAY['notifications.read','notifications.manage_preferences','notifications.mark_read'],'ACTIVE'),
 ('u1b','m1','User One B','oneb@example.invalid','oneb@example.invalid','x','OWNER',ARRAY['notifications.read','notifications.manage_preferences','notifications.mark_read'],'ACTIVE'),
 ('u2','m2','User Two','two@example.invalid','two@example.invalid','x','OWNER',ARRAY['notifications.read','notifications.manage_preferences','notifications.mark_read'],'ACTIVE'),
 ('limited','m1','Limited','limited@example.invalid','limited@example.invalid','x','SUPPORT',ARRAY[]::text[],'ACTIVE'),
 ('disabled','m1','Disabled','disabled@example.invalid','disabled@example.invalid','x','OWNER',ARRAY['notifications.read'],'SUSPENDED'),
 ('platform',NULL,'Platform','platform@example.invalid','platform@example.invalid','x','PLATFORM_ADMIN',ARRAY['platform.notifications.read','platform.notifications.delivery.read','platform.notifications.delivery.retry','platform.notifications.templates.read'],'ACTIVE'),
 ('platformlimited',NULL,'Platform Limited','pl@example.invalid','pl@example.invalid','x','PLATFORM_ADMIN',ARRAY[]::text[],'ACTIVE');
 `);for(const [t,u] of [['u1-token','u1'],['u1b-token','u1b'],['u2-token','u2'],['limited-token','limited'],['disabled-token','disabled'],['platform-token','platform'],['platformlimited-token','platformlimited']] as const)await db.query(`INSERT INTO sessions(token_hash,user_id,expires_at,absolute_expires_at,last_seen_at) VALUES($1,$2,now()+interval '1 hour',now()+interval '2 hours',now())`,[tokenHash(t),u]);app=await buildApp(loadConfig({NODE_ENV:'test',DATABASE_URL:url!,PASSWORD_PEPPER:'p'.repeat(32),COOKIE_SECRET:'c'.repeat(32),FRONTEND_ORIGIN:'http://127.0.0.1:5173',PAYMENT_PROVIDER:'sandbox',SANDBOX_WEBHOOK_SECRET:'w'.repeat(32)}),db,undefined,undefined,new MemoryRateLimitStore());});
 afterAll(async()=>{await app?.close();await db?.end();await admin?.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin?.end();});

 it('enforces controlled values, unique template versions, immutable ownership, and statement-level append-only history',async()=>{await expect(db.query(`INSERT INTO notification_templates VALUES('bad',1,'BAD','IN_APP','MERCHANT_USER',NULL,'x','{}',true,now(),NULL)`)).rejects.toThrow();await expect(db.query(`INSERT INTO notification_templates VALUES('bad',1,'SYSTEM','PUSH','MERCHANT_USER',NULL,'x','{}',true,now(),NULL)`)).rejects.toThrow();await expect(db.query(`INSERT INTO notification_templates(template_key,version,category,channel,audience_type,body_template) VALUES('generic.merchant.event',1,'SYSTEM','IN_APP','MERCHANT_USER','x')`)).rejects.toThrow();for(const table of ['notification_templates','notification_delivery_attempts','notification_read_history','notification_event_receipts']){const column=table==='notification_templates'?'template_key':table==='notification_event_receipts'?'outbox_event_id':'id';await expect(db.query(`UPDATE ${table} SET ${column}=${column} WHERE false`),table).rejects.toThrow(/append-only/i);await expect(db.query(`DELETE FROM ${table} WHERE false`),table).rejects.toThrow(/append-only/i);}});
 it('denies unauthenticated, permissionless, disabled, API-key, and cross-authority access',async()=>{expect((await app.inject({url:'/v1/notifications'})).statusCode).toBe(401);expect((await app.inject({url:'/v1/notifications',headers:human('limited-token')})).statusCode).toBe(403);expect((await app.inject({url:'/v1/notifications',headers:human('disabled-token')})).statusCode).toBe(401);expect((await app.inject({url:'/v1/notifications',headers:{authorization:'Bearer fake'}})).statusCode).toBe(403);expect((await app.inject({url:'/v1/notifications',headers:human('platform-token')})).statusCode).toBe(403);expect((await app.inject({url:'/v1/platform/notification-deliveries',headers:human('u1-token')})).statusCode).toBe(403);expect((await app.inject({url:'/v1/platform/notification-deliveries',headers:human('platformlimited-token')})).statusCode).toBe(403);});
 it('creates exactly one safe in-app notification under duplicate and concurrent event consumption',async()=>{const ids=await Promise.all(Array.from({length:8},()=>createNotificationFromEvent(db,event('one'),'u1')));expect(new Set(ids).size).toBe(1);notificationId=ids[0]!;const row=(await db.query('SELECT * FROM notifications WHERE id=$1',[notificationId])).rows[0];expect(row).toMatchObject({recipient_user_id:'u1',merchant_id:'m1',template_key:'generic.merchant.event',template_version:1,delivery_state:'DELIVERED',related_entity_type:'support_case'});expect(JSON.stringify(row)).not.toMatch(/internalNote|secret@example/);expect(Number((await db.query('SELECT count(*) FROM notification_event_receipts WHERE notification_id=$1',[notificationId])).rows[0].count)).toBe(1);});
 it('rejects missing and unknown variables, escapes unsafe content, and enforces rendered length',()=>{expect(()=>renderTemplate('Hi {{name}}',['name'],{})).toThrow('TEMPLATE_VARIABLE_MISMATCH');expect(()=>renderTemplate('Hi {{name}}',['name'],{name:'x',extra:'y'})).toThrow('TEMPLATE_VARIABLE_MISMATCH');expect(renderTemplate('{{name}}',['name'],{name:'<script>alert(1)</script>'})).not.toContain('<script>');expect(()=>renderTemplate('{{value}}',['value'],{value:'x'.repeat(101)},100)).toThrow('TEMPLATE_RENDER_INVALID');});
 it('isolates merchant and user inboxes, unread counts, and non-enumerating lookups',async()=>{await createNotificationFromEvent(db,event('other-user'),'u1b');await createNotificationFromEvent(db,event('other-tenant'),'u2');const mine=await app.inject({url:'/v1/notifications',headers:human('u1-token')}),other=await app.inject({url:'/v1/notifications',headers:human('u2-token')});expect(mine.json().data).toHaveLength(1);expect(other.json().data).toHaveLength(1);expect((await app.inject({url:'/v1/notifications/unread-count',headers:human('u1-token')})).json().count).toBe(1);expect((await app.inject({method:'POST',url:`/v1/notifications/${notificationId}/read`,headers:idem('u2-token','cross-user-read')})).statusCode).toBe(404);});
 it('marks read idempotently, conflicts on changed key input, and creates one history/audit effect under concurrency',async()=>{const call=()=>app.inject({method:'POST',url:`/v1/notifications/${notificationId}/read`,headers:idem('u1-token','mark-read-one'),payload:{}}),results=await Promise.all(Array.from({length:5},()=>call()));expect(results.every(x=>x.statusCode===200),results.map(x=>x.body).join('\n')).toBe(true);expect(results.every(x=>x.body===results[0]!.body)).toBe(true);expect(Number((await db.query('SELECT count(*) FROM notification_read_history WHERE notification_id=$1',[notificationId])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE resource_id=$1 AND action='NOTIFICATION_READ'`,[notificationId])).rows[0].count)).toBe(1);expect((await app.inject({method:'POST',url:`/v1/notifications/${notificationId}/read`,headers:idem('u1-token','mark-read-one'),payload:{expectedUnread:false}})).statusCode).toBe(409);expect((await app.inject({url:'/v1/notifications/unread-count',headers:human('u1-token')})).json().count).toBe(0);});
 it('mark-all affects only the authenticated user and replays without duplicate effects',async()=>{await createNotificationFromEvent(db,event('all-a'),'u1');await createNotificationFromEvent(db,event('all-b'),'u1');const call=()=>app.inject({method:'POST',url:'/v1/notifications/read-all',headers:idem('u1-token','read-all-one'),payload:{}}),a=await call(),b=await call();expect(a.statusCode,a.body).toBe(200);expect(b.json()).toEqual(a.json());expect((await app.inject({url:'/v1/notifications/unread-count',headers:human('u1-token')})).json().count).toBe(0);expect((await app.inject({url:'/v1/notifications/unread-count',headers:human('u1b-token')})).json().count).toBeGreaterThan(0);});
 it('returns effective preferences, protects mandatory in-app policy, versions updates, and honestly labels external channels unavailable',async()=>{const initial=await app.inject({url:'/v1/notifications/preferences',headers:human('u1-token')});expect(initial.statusCode).toBe(200);expect(initial.json().data.find((x:any)=>x.category==='SECURITY'&&x.channel==='IN_APP')).toMatchObject({effectiveEnabled:true,mandatory:true});expect((await app.inject({method:'PATCH',url:'/v1/notifications/preferences',headers:idem('u1-token','mandatory-off'),payload:{category:'SECURITY',channel:'IN_APP',enabled:false,expectedVersion:0}})).statusCode).toBe(409);const update=()=>app.inject({method:'PATCH',url:'/v1/notifications/preferences',headers:idem('u1-token','payment-email-pref'),payload:{category:'PAYMENT',channel:'EMAIL',enabled:true,expectedVersion:0}}),a=await update(),b=await update();expect(a.statusCode,a.body).toBe(200);expect(b.json()).toEqual(a.json());expect(a.json()).toMatchObject({channelAvailable:false,externalDeliveryAvailable:false});expect((await app.inject({method:'PATCH',url:'/v1/notifications/preferences',headers:idem('u1-token','stale-pref'),payload:{category:'PAYMENT',channel:'EMAIL',enabled:false,expectedVersion:0}})).statusCode).toBe(409);expect((await app.inject({method:'PATCH',url:'/v1/notifications/preferences',headers:idem('u1-token','payment-email-pref'),payload:{category:'PAYMENT',channel:'EMAIL',enabled:false,expectedVersion:1}})).statusCode).toBe(409);});
 it('claims with leases exactly once and records honest disabled attempts without network delivery',async()=>{const ntf=await createNotificationFromEvent(db,event('external'),'u1');await db.query(`UPDATE notification_delivery_jobs SET state='DISABLED' WHERE notification_id=$1`,[ntf]);await db.query(`INSERT INTO notification_templates(template_key,version,category,channel,audience_type,body_template,required_variables) VALUES('test.email',1,'SYSTEM','EMAIL','MERCHANT_USER','Notice {{entityId}}','{entityId}')`);const eid=`ntf_${randomUUID().replaceAll('-','')}`,jid=`ndj_${randomUUID().replaceAll('-','')}`;await db.query(`INSERT INTO notifications(id,authority,merchant_id,recipient_user_id,category,template_key,template_version,title,body,channel,delivery_state,related_entity_type,related_entity_id,deduplication_key) VALUES($1,'MERCHANT','m1','u1','SYSTEM','test.email',1,'Notice','Safe body','EMAIL','PENDING','support_case','case-x',$2)`,[eid,`dedupe-${eid}`]);await db.query(`INSERT INTO notification_delivery_jobs(id,notification_id,channel,state) VALUES($1,$2,'EMAIL','PENDING')`,[jid,eid]);const w1=new NotificationDeliveryWorker(db),w2=new NotificationDeliveryWorker(db),claims=(await Promise.all([w1.claim('w1'),w2.claim('w2')])).flat();expect(claims.filter(x=>x.id===jid)).toHaveLength(1);const claim=claims.find(x=>x.id===jid)!;expect(await (claim.lease_owner==='w1'?w1:w2).finishDisabled(jid,claim.lease_owner)).toBe('DISABLED');expect((await db.query('SELECT state,last_error_code FROM notification_delivery_jobs WHERE id=$1',[jid])).rows[0]).toMatchObject({state:'DISABLED',last_error_code:'PROVIDER_DISABLED'});expect(Number((await db.query('SELECT count(*) FROM notification_delivery_attempts WHERE job_id=$1',[jid])).rows[0].count)).toBe(1);await expect(db.query(`UPDATE notification_delivery_jobs SET state='SENT' WHERE id=$1`,[jid])).rejects.toThrow();});
 it('recovers expired leases but never steals live leases and excludes terminal or cancelled jobs',async()=>{const make=async(state:string,lease:string|null)=>{const nid=`ntf_${randomUUID().replaceAll('-','')}`,jid=`ndj_${randomUUID().replaceAll('-','')}`;await db.query(`INSERT INTO notifications(id,authority,merchant_id,recipient_user_id,category,template_key,template_version,title,body,channel,delivery_state,deduplication_key) VALUES($1,'MERCHANT','m1','u1','SYSTEM','generic.merchant.event',1,'x','x','IN_APP','PENDING',$2)`,[nid,nid]);await db.query(`INSERT INTO notification_delivery_jobs(id,notification_id,channel,state,lease_owner,lease_expires_at) VALUES($1,$2,'IN_APP',$3,'old',$4)`,[jid,nid,state,lease]);return jid;};const expired=await make('DEFERRED','2000-01-01'),live=await make('DEFERRED','2999-01-01'),cancelled=await make('CANCELLED',null);const rows=await new NotificationDeliveryWorker(db).claim('recovery',100);expect(rows.some(x=>x.id===expired)).toBe(true);expect(rows.some(x=>x.id===live||x.id===cancelled)).toBe(false);});
 it('redacts platform projections, denies disabled-provider retry, and validates expected state and reason',async()=>{const list=await app.inject({url:'/v1/platform/notification-deliveries',headers:human('platform-token')});expect(list.statusCode,list.body).toBe(200);expect(list.body).not.toContain('one@example.invalid');const email=(await db.query(`SELECT id,state FROM notification_delivery_jobs WHERE channel='EMAIL' LIMIT 1`)).rows[0];expect((await app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${email.id}/retry`,headers:idem('platform-token','retry-short'),payload:{expectedState:email.state,reason:'x'}})).statusCode).toBe(422);expect((await app.inject({method:'POST',url:`/v1/platform/notification-deliveries/${email.id}/retry`,headers:idem('platform-token','retry-disabled'),payload:{expectedState:email.state,reason:'Operational retry request'}})).statusCode).toBe(409);});
 it('uses stable same-timestamp cursor pagination and rejects invalid cursors, page sizes, and reversed dates',async()=>{await db.query(`UPDATE notifications SET created_at='2026-01-01T00:00:00Z' WHERE recipient_user_id='u1'`);const p1=await app.inject({url:'/v1/notifications?limit=2',headers:human('u1-token')});expect(p1.statusCode).toBe(200);const p2=await app.inject({url:`/v1/notifications?limit=2&cursor=${encodeURIComponent(p1.json().nextCursor)}`,headers:human('u1-token')});expect(new Set([...p1.json().data,...p2.json().data].map((x:any)=>x.id)).size).toBe(p1.json().data.length+p2.json().data.length);expect((await app.inject({url:'/v1/notifications?cursor=bad',headers:human('u1-token')})).statusCode).toBe(400);expect((await app.inject({url:'/v1/notifications?limit=101',headers:human('u1-token')})).statusCode).toBe(422);expect((await app.inject({url:'/v1/notifications?from=2026-02-01T00:00:00.000Z&to=2026-01-01T00:00:00.000Z',headers:human('u1-token')})).statusCode).toBe(400);});
 it('keeps audit and outbox metadata free of bodies, contact details, tokens, and secrets',async()=>{const data=JSON.stringify((await db.query(`SELECT metadata FROM audit_events WHERE action LIKE 'NOTIFICATION_%' UNION ALL SELECT payload FROM outbox_events WHERE aggregate_type='notification'`)).rows);expect(data).not.toMatch(/example\.invalid|Safe body|secret|token|telephone|<script>/i);});
 it('rolls back notification mutation work atomically when a transaction fails',async()=>{const before=Number((await db.query('SELECT count(*) FROM notification_read_history')).rows[0].count);await expect((async()=>{const c=await db.connect();try{await c.query('BEGIN');await c.query(`INSERT INTO notification_read_history(id,notification_id,user_id) SELECT $1,id,'u1b' FROM notifications WHERE recipient_user_id='u1b' LIMIT 1`,[`nrh_${randomUUID()}`]);await c.query(`INSERT INTO audit_events(id,actor_id,merchant_id,action,resource_type,resource_id) VALUES($1,'u1b','m1','NOTIFICATION_READ','notification','rollback')`,[`aud_${randomUUID()}`]);throw new Error('injected rollback');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}})()).rejects.toThrow('injected rollback');expect(Number((await db.query('SELECT count(*) FROM notification_read_history')).rows[0].count)).toBe(before);expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE resource_id='rollback'`)).rows[0].count)).toBe(0);});
});
