import 'dotenv/config';
import { randomUUID } from 'node:crypto';
import { readFile,readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import pg from 'pg';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { MemoryRateLimitStore } from '../src/rateLimit.js';
import { tokenHash } from '../src/security.js';
import { apiKeyVerifier,generateApiKey } from '../src/developer/apiKeys.js';
import { requireSafeTestDatabase } from './integrationGuard.js';

const url=process.env.TEST_DATABASE_URL?requireSafeTestDatabase(process.env.TEST_DATABASE_URL,process.env.ALLOW_REMOTE_TEST_DATABASE==='true').toString():undefined,suite=url?describe:describe.skip,schema=`onboarding_test_${randomUUID().replaceAll('-','')}`;
let admin:pg.Pool,db:pg.Pool,app:Awaited<ReturnType<typeof buildApp>>,applicationId:string;
const session=(token:string)=>({cookie:`giantpay_session=${token}; giantpay_csrf=c`,origin:'http://127.0.0.1:5173','x-csrf-token':'c'});
const profile={legalName:'Fictional Merchant Limited',tradingName:'Fictional Shop',registrationNumber:'TEST-REG-0001',taxIdentifier:'TEST-TAX-0001',businessType:'LIMITED_COMPANY',industry:'Software testing',incorporationCountry:'MW',operatingCountry:'MW',contactEmail:'compliance@example.invalid',contactPhone:'+265999000001',website:'https://example.invalid',expectedMonthlyVolumeMin:1,expectedMonthlyVolumeMax:100,expectedMonthlyValueMin:1000,expectedMonthlyValueMax:1000000,intendedChannels:['CARD'],settlementAccountReference:'SANDBOX-ACCOUNT-0001'};
suite('merchant onboarding and compliance controls',()=>{
 beforeAll(async()=>{admin=new pg.Pool({connectionString:url!});await admin.query(`CREATE SCHEMA ${schema}`);db=new pg.Pool({connectionString:url!,options:`-c search_path=${schema}`});for(const name of (await readdir(resolve('migrations'))).filter(x=>x.endsWith('.sql')).sort())await db.query(await readFile(resolve('migrations',name),'utf8'));await db.query(`INSERT INTO merchants(id,name) VALUES('m1','One'),('m2','Two');INSERT INTO users(id,merchant_id,name,email,normalized_email,password_hash,role,permissions,status) VALUES('owner','m1','Owner','owner@example.invalid','owner@example.invalid','x','OWNER',ARRAY['onboarding:read','onboarding:write','onboarding:submit'],'ACTIVE'),('other','m2','Other','other@example.invalid','other@example.invalid','x','OWNER',ARRAY['onboarding:read','onboarding:write','onboarding:submit'],'ACTIVE'),('reviewer',NULL,'Reviewer','reviewer@example.invalid','reviewer@example.invalid','x','PLATFORM_ADMIN',ARRAY['compliance:read','compliance:review','compliance:approve'],'ACTIVE'),('approver',NULL,'Approver','approver@example.invalid','approver@example.invalid','x','PLATFORM_ADMIN',ARRAY['compliance:read','compliance:review','compliance:approve'],'ACTIVE')`);for(const [token,user] of [['owner-token','owner'],['other-token','other'],['review-token','reviewer'],['approve-token','approver']] as const)await db.query(`INSERT INTO sessions(token_hash,user_id,expires_at,absolute_expires_at,last_seen_at) VALUES($1,$2,now()+interval '1 hour',now()+interval '2 hours',now())`,[tokenHash(token),user]);app=await buildApp(loadConfig({NODE_ENV:'test',DATABASE_URL:url!,PASSWORD_PEPPER:'p'.repeat(32),COOKIE_SECRET:'c'.repeat(32),FRONTEND_ORIGIN:'http://127.0.0.1:5173',PAYMENT_PROVIDER:'sandbox',SANDBOX_WEBHOOK_SECRET:'w'.repeat(32)}),db,undefined,undefined,new MemoryRateLimitStore());});
 afterAll(async()=>{await app?.close();await db?.end();await admin?.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin?.end();});
 it('creates an encrypted tenant-scoped draft and denies API keys',async()=>{const created=await app.inject({method:'PATCH',url:'/v1/merchants/onboarding',headers:session('owner-token'),payload:profile});expect(created.statusCode,created.body).toBe(200);applicationId=created.json().id;const stored=(await db.query('SELECT * FROM onboarding_business_profiles WHERE application_id=$1',[applicationId])).rows[0];expect(stored.registration_number_ciphertext).not.toContain(profile.registrationNumber);expect(stored.registration_number_masked).toMatch(/0001$/);expect((await app.inject({url:'/v1/merchants/onboarding',headers:session('other-token')})).statusCode).toBe(404);const key=generateApiKey();await db.query(`INSERT INTO api_keys(id,public_id,merchant_id,name,verifier,fingerprint,scopes,created_by) VALUES('onboarding-key',$1,'m1','Onboarding',$2,$3,ARRAY['payments:read'],'owner')`,[key.publicId,apiKeyVerifier(key.plaintext,'p'.repeat(32)),key.fingerprint]);expect((await app.inject({method:'PATCH',url:'/v1/merchants/onboarding',headers:{authorization:`Bearer ${key.plaintext}`,'content-type':'application/json'},payload:profile})).statusCode).toBe(403);});
 it('validates people, ownership boundaries, questionnaire version and document metadata',async()=>{const post=async(url:string,payload:unknown):Promise<any>=>await app.inject({method:'POST',url,headers:session('owner-token'),payload:payload as any});expect((await post('/v1/merchants/onboarding/beneficial-owners',{fullName:'Invalid Owner',nationality:'MW',ownershipBasisPoints:10001})).statusCode).toBe(400);expect((await post('/v1/merchants/onboarding/directors',{fullName:'Director One',email:'director@example.invalid',nationality:'MW',identificationNumber:'TEST-ID-DIRECTOR'})).statusCode).toBe(201);expect((await post('/v1/merchants/onboarding/beneficial-owners',{fullName:'Owner One',email:'beneficial@example.invalid',nationality:'MW',ownershipBasisPoints:10000,identificationNumber:'TEST-ID-OWNER'})).statusCode).toBe(201);expect((await post('/v1/merchants/onboarding/authorized-representatives',{fullName:'Representative One',email:'representative@example.invalid',telephone:'+265999000002',authority:'Authorized sandbox representative'})).statusCode).toBe(201);for(const kind of ['REGISTERED','OPERATING'])expect((await post('/v1/merchants/onboarding/addresses',{kind,line1:`${kind} fictional address`,city:'Lilongwe',country:'MW'})).statusCode).toBe(201);const questionnaire=await app.inject({method:'PUT',url:'/v1/merchants/onboarding/questionnaire',headers:session('owner-token'),payload:{version:'2026-01',declarationAccepted:true,answers:{natureOfBusiness:'Fictional software testing services',sourceOfFunds:'Fictional customer service revenue',expectedPaymentActivity:'Low-volume sandbox card transactions',countriesOfOperation:['MW'],politicallyExposedPerson:false,sanctionsDeclaration:false,highRiskBusiness:false,thirdPartyPaymentProcessing:false,refundAndDisputeExpectations:'Occasional sandbox refunds for tests'}}});expect(questionnaire.statusCode,questionnaire.body).toBe(200);const unsafe=await post('/v1/merchants/onboarding/evidence',{category:'BUSINESS_REGISTRATION',ownerType:'MERCHANT',storageReference:'sandbox/object/unsafe',mediaType:'application/octet-stream',sizeBytes:100,sha256:'a'.repeat(64),fileName:'payload.exe'});expect(unsafe.statusCode).toBe(400);const evidence=await post('/v1/merchants/onboarding/evidence',{category:'BUSINESS_REGISTRATION',ownerType:'MERCHANT',storageReference:'sandbox/object/evidence-1',mediaType:'application/pdf',sizeBytes:100,sha256:'a'.repeat(64),fileName:'registration.pdf'});expect(evidence.statusCode,evidence.body).toBe(201);expect(JSON.stringify(evidence.json())).not.toContain('sandbox/object/evidence-1');});
 it('submits idempotently, stores one immutable snapshot and one atomic audit/outbox effect',async()=>{const submit=()=>app.inject({method:'POST',url:'/v1/merchants/onboarding/submit',headers:{...session('owner-token'),'idempotency-key':'submission-one'}}),responses=await Promise.all([submit(),submit()]);expect(responses.every(x=>x.statusCode===200),responses.map(x=>x.body).join('\n')).toBe(true);expect(new Set(responses.map(x=>x.body)).size).toBe(1);expect((await db.query('SELECT status FROM onboarding_applications WHERE id=$1',[applicationId])).rows[0].status).toBe('SUBMITTED');expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE action='ONBOARDING_SUBMITTED' AND resource_id=$1`,[applicationId])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM outbox_events WHERE aggregate_id=$1 AND event_type='onboarding.submitted'`,[applicationId])).rows[0].count)).toBe(1);expect((await app.inject({method:'PATCH',url:'/v1/merchants/onboarding',headers:session('owner-token'),payload:profile})).statusCode).toBe(409);await expect(db.query(`UPDATE onboarding_business_profiles SET legal_name='Changed' WHERE application_id=$1`,[applicationId])).rejects.toThrow(/immutable/i);});
 it('isolates compliance authority and enforces maker-checker review',async()=>{expect((await app.inject({url:'/v1/compliance/applications',headers:session('owner-token')})).statusCode).toBe(403);const start=await app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/review`,headers:session('review-token')});expect(start.statusCode,start.body).toBe(200);const self=await app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/approve`,headers:{...session('review-token'),'idempotency-key':'approve-self'},payload:{reason:'Sandbox evidence was reviewed internally',evidenceReference:'review-note-1'}});expect(self.statusCode,self.body).toBe(409);expect(self.json().error.code).toBe('COMPLIANCE_MAKER_CHECKER_REQUIRED');});
 it('records risk evidence and an information-request/resubmission lifecycle',async()=>{const risk=await app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/risk-classifications`,headers:session('review-token'),payload:{classification:'LOW',reason:'Fictional low-risk sandbox assessment',evidenceReference:'risk-note-1'}});expect(risk.statusCode,risk.body).toBe(201);const request=await app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/information-requests`,headers:{...session('review-token'),'idempotency-key':'info-request-one'},payload:{reason:'Please clarify the fictional operating address',evidenceReference:'review-note-2'}});expect(request.statusCode,request.body).toBe(201);const response=await app.inject({method:'POST',url:'/v1/merchants/onboarding/information-response',headers:session('owner-token'),payload:{requestId:request.json().id,response:'The address is a fictional test location only.'}});expect(response.statusCode,response.body).toBe(200);const resubmit=await app.inject({method:'POST',url:'/v1/merchants/onboarding/resubmit',headers:session('owner-token')});expect(resubmit.statusCode,resubmit.body).toBe(200);expect(resubmit.json().status).toBe('RESUBMITTED');});
 it('allows exactly one concurrent review transition and one concurrent decision',async()=>{const review=()=>app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/review`,headers:session('review-token')}),reviews=await Promise.all([review(),review()]);expect(reviews.filter(x=>x.statusCode===200)).toHaveLength(1);expect(reviews.filter(x=>x.statusCode===409)).toHaveLength(1);const decision=(kind:string,token:string,key:string)=>app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/${kind}`,headers:{...session(token),'idempotency-key':key},payload:{reason:`Fictional ${kind} decision with evidence`,evidenceReference:`decision-${kind}`}}),decisions=await Promise.all([decision('approve','approve-token','decision-approve'),decision('reject','review-token','decision-reject')]);expect(decisions.filter(x=>x.statusCode===200)).toHaveLength(1);expect(decisions.filter(x=>x.statusCode===409)).toHaveLength(1);const winner=decisions.find(x=>x.statusCode===200)!;if(winner.json().status==='APPROVED')expect(winner.json().message).toContain('Internal sandbox decision only');});
 it('requires reasons and evidence for rejection and suspension and keeps history append-only',async()=>{const status=(await db.query('SELECT status FROM onboarding_applications WHERE id=$1',[applicationId])).rows[0].status;if(status==='APPROVED'){const bad=await app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/suspend`,headers:{...session('review-token'),'idempotency-key':'bad-suspend'},payload:{reason:'short',evidenceReference:''}});expect(bad.statusCode).toBe(400);const good=await app.inject({method:'POST',url:`/v1/compliance/applications/${applicationId}/suspend`,headers:{...session('review-token'),'idempotency-key':'good-suspend'},payload:{reason:'Sandbox access suspended following internal review',evidenceReference:'suspension-note'}});expect(good.statusCode,good.body).toBe(200);}await expect(db.query(`DELETE FROM onboarding_status_transitions WHERE application_id=$1`,[applicationId])).rejects.toThrow(/append-only/i);await expect(db.query(`DELETE FROM onboarding_review_decisions WHERE application_id=$1`,[applicationId])).rejects.toThrow(/append-only/i);});
 it('rolls back application, audit and outbox state on a required audit failure',async()=>{await db.query(`CREATE FUNCTION reject_phase6_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='ONBOARDING_DRAFT_CREATED' THEN RAISE EXCEPTION 'forced audit failure'; END IF; RETURN NEW; END $$`);await db.query(`CREATE TRIGGER reject_phase6_audit BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_phase6_audit()`);const response=await app.inject({method:'PATCH',url:'/v1/merchants/onboarding',headers:session('other-token'),payload:{...profile,contactEmail:'other-merchant@example.invalid'}});expect(response.statusCode).toBe(500);expect(Number((await db.query(`SELECT count(*) FROM onboarding_applications WHERE merchant_id='m2'`)).rows[0].count)).toBe(0);expect(Number((await db.query(`SELECT count(*) FROM outbox_events WHERE payload->>'merchantId'='m2'`)).rows[0].count)).toBe(0);await db.query('DROP TRIGGER reject_phase6_audit ON audit_events');});
});
