import {describe,expect,it,vi} from 'vitest';
import {MetricsRegistry,operationalMetrics} from '../src/operations/metrics.js';
import {GracefulLifecycle,ShutdownCoordinator} from '../src/operations/lifecycle.js';
import {assertDisposableRestoreTarget,verifyLedgerIntegrity} from '../src/operations/recovery.js';
import {workerAllowed} from '../src/operations/controls.js';
import {decryptVersionedSecret,encryptVersionedSecret} from '../src/developer/webhookSecurity.js';
import {NotificationDeliveryWorker} from '../src/notifications/service.js';

describe('Phase 10 operational primitives',()=>{
 it('records every bounded Phase 10 metric category and rejects sensitive labels',()=>{const metrics=new MetricsRegistry();metrics.increment('http_requests_total',{method:'GET',route:'/v1/incidents/:id',statusClass:'2xx'});metrics.duration('http_request_duration_ms',{method:'GET',route:'/v1/incidents/:id'},12);metrics.increment('dependency_checks_total',{dependency:'postgresql',outcome:'available'});metrics.increment('idempotency_requests_total',{operation:'operations',outcome:'replay'});metrics.increment('operational_incidents_total',{state:'declared',severity:'sev2'});metrics.increment('operational_control_decisions_total',{decision:'approved',control:'payment_creation_paused'});metrics.increment('graceful_shutdown_total',{outcome:'completed'});expect(Object.keys(metrics.snapshot().counters)).toHaveLength(6);for(const unsafe of ['person@example.com','+265991234567','gp_live_secret','bearer-secret','/v1/payments/pay_123456789012345678901234'])expect(()=>metrics.increment('http_requests_total',{method:'GET',route:unsafe,statusClass:'2xx'})).toThrow('UNSAFE_METRIC_LABEL');expect(()=>metrics.increment('custom_metric_total',{merchantId:'m1'})).toThrow('UNSAFE_METRIC_LABEL');const bounded=new MetricsRegistry(2);bounded.increment('http_requests_total',{method:'GET',route:'/one',statusClass:'2xx'});bounded.increment('http_requests_total',{method:'GET',route:'/two',statusClass:'2xx'});expect(()=>bounded.increment('http_requests_total',{method:'GET',route:'/three',statusClass:'2xx'})).toThrow('METRIC_CARDINALITY_LIMIT');});
 it('stops claims, bounds draining, closes dependencies, records state, and makes repeated shutdown safe',async()=>{vi.useFakeTimers();operationalMetrics.reset();const calls:string[]=[];let release!:()=>void;const drain=new Promise<void>(r=>release=r);const lifecycle=new GracefulLifecycle([{name:'worker',stopClaims:()=>{calls.push('stop');},drain:()=>drain,close:async()=>{calls.push('close');}}],25);const first=lifecycle.shutdown(),second=lifecycle.shutdown();expect(first).toBe(second);await vi.advanceTimersByTimeAsync(25);await expect(first).resolves.toEqual({timedOut:true});expect(calls).toEqual(['stop','close']);expect(operationalMetrics.snapshot().counters).toMatchObject({'graceful_shutdown_total{outcome=started}':1,'graceful_shutdown_total{outcome=timed_out}':1});release();vi.useRealTimers();});
 it('graceful shutdown closes HTTP, Redis, and PostgreSQL dependencies after stopping claims',async()=>{const calls:string[]=[];const lifecycle=new GracefulLifecycle([{name:'http',stopClaims:()=>{calls.push('readiness-off');},close:async()=>{calls.push('http-close');}},{name:'redis',close:async()=>{calls.push('redis-close');}},{name:'postgresql',close:async()=>{calls.push('postgresql-close');}}],100);await expect(lifecycle.shutdown()).resolves.toEqual({timedOut:false});expect(calls[0]).toBe('readiness-off');expect(calls).toEqual(expect.arrayContaining(['http-close','redis-close','postgresql-close']));});
 it('forces termination after the shutdown deadline without terminating the test runner',async()=>{vi.useFakeTimers();const force=vi.fn(),logs:Record<string,string|boolean>[]=[];const never=new Promise<{timedOut:boolean}>(()=>undefined),coordinator=new ShutdownCoordinator({shutdown:()=>never},50,force,entry=>logs.push(entry));const first=coordinator.shutdown('SIGTERM'),second=coordinator.shutdown('SIGINT');expect(first).toBe(second);await vi.advanceTimersByTimeAsync(50);expect(force).toHaveBeenCalledWith(1);expect(logs).toEqual([{event:'shutdown_started',signal:'SIGTERM'},{event:'shutdown_forced',reason:'deadline_exceeded'}]);vi.useRealTimers();});
 it('fails closed when worker control state cannot be verified',async()=>{const db={query:vi.fn().mockRejectedValue(new Error('database unavailable'))};await expect(workerAllowed(db as any,'OUTBOX_PROCESSING_PAUSED')).resolves.toBe(false);});
 it('prevents notification workers from claiming when operational controls are active',async()=>{const db={query:vi.fn()};const worker=new NotificationDeliveryWorker(db as any,60,async()=>false);await expect(worker.claim('worker-a')).resolves.toEqual([]);expect(db.query).not.toHaveBeenCalled();});
 it('accepts only disposable restore databases ending in _test',()=>{expect(assertDisposableRestoreTarget('postgresql://localhost/restore_test')).toBe('restore_test');expect(()=>assertDisposableRestoreTarget('postgresql://localhost/production')).toThrow('RESTORE_TARGET_MUST_BE_DISPOSABLE_TEST_DATABASE');});
 it('detects ledger imbalance during restore verification',async()=>{const db={query:vi.fn().mockResolvedValue({rowCount:1,rows:[{transaction_id:'txn_1',currency:'MWK',balance:100}]})};await expect(verifyLedgerIntegrity(db as any)).rejects.toThrow('LEDGER_INTEGRITY_CHECK_FAILED');});
 it('decrypts known key versions and fails closed for unknown versions',()=>{const material='a'.repeat(32),value=encryptVersionedSecret('secret','v1',material);expect(decryptVersionedSecret(value,{v1:material})).toBe('secret');expect(()=>decryptVersionedSecret(value,{v2:'b'.repeat(32)})).toThrow('UNKNOWN_KEY_VERSION');});
});
