import 'dotenv/config';
import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import pg from 'pg';
import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import {buildApp} from '../src/app.js';
import {loadConfig} from '../src/config.js';
import {MemoryRateLimitStore} from '../src/rateLimit.js';
import {tokenHash} from '../src/security.js';
import {requireSafeTestDatabase} from './integrationGuard.js';

const url=process.env.TEST_DATABASE_URL?requireSafeTestDatabase(process.env.TEST_DATABASE_URL,process.env.ALLOW_REMOTE_TEST_DATABASE==='true').toString():undefined;
const suite=url?describe:describe.skip,schema=`reporting_test_${randomUUID().replaceAll('-','')}`,start='2026-09-01T00:00:00.000Z',end='2026-09-02T00:00:00.000Z';
let admin:pg.Pool,db:pg.Pool,app:Awaited<ReturnType<typeof buildApp>>;
const session=(token:string)=>({cookie:`giantpay_session=${token}; giantpay_csrf=csrf`,origin:'http://127.0.0.1:5173','x-csrf-token':'csrf'});
const post=(token:string,key:string,payload:any)=>({method:'POST' as const,headers:{...session(token),'content-type':'application/json','idempotency-key':key},payload,url:'/v1/report-exports'});
const payload={reportType:'TRANSACTION_ACTIVITY',currency:'MWK',periodStart:start,periodEnd:end};
suite('reporting operations database controls',()=>{
  beforeAll(async()=>{admin=new pg.Pool({connectionString:url!});await admin.query(`CREATE SCHEMA ${schema}`);db=new pg.Pool({connectionString:url!,options:`-c search_path=${schema}`});for(const name of (await readdir(resolve('migrations'))).filter(x=>x.endsWith('.sql')).sort())await db.query(await readFile(resolve('migrations',name),'utf8'));await db.query(`INSERT INTO merchants(id,name) VALUES('m1','One'),('m2','Two')`);const permissions=['reports:read','reports:export','audit:read'];await db.query(`INSERT INTO users(id,merchant_id,name,email,password_hash,role,permissions) VALUES('u1','m1','One','one@test.invalid','x','OWNER',$1),('u2','m2','Two','two@test.invalid','x','OWNER',$1),('viewer','m1','Viewer','viewer@test.invalid','x','ANALYST','{}')`,[permissions]);for(const [token,user] of [['one-token','u1'],['two-token','u2'],['viewer-token','viewer']] as const)await db.query(`INSERT INTO sessions(token_hash,user_id,expires_at,absolute_expires_at,last_seen_at) VALUES($1,$2,now()+interval '1 hour',now()+interval '2 hours',now())`,[tokenHash(token),user]);app=await buildApp(loadConfig({NODE_ENV:'test',DATABASE_URL:url!,PASSWORD_PEPPER:'p'.repeat(32),COOKIE_SECRET:'c'.repeat(32),FRONTEND_ORIGIN:'http://127.0.0.1:5173',PAYMENT_PROVIDER:'sandbox',SANDBOX_WEBHOOK_SECRET:'w'.repeat(32)}),db,undefined,undefined,new MemoryRateLimitStore());});
  afterAll(async()=>{await app?.close();await db?.end();await admin?.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin?.end();});
  beforeEach(async()=>{await db.query('TRUNCATE report_exports,audit_events,journal_postings,journal_entries,ledger_accounts,refunds,payments CASCADE');await db.query(`INSERT INTO payments(id,merchant_id,reference,status,channel,gross_minor,fee_minor,refunded_minor,currency,created_at,updated_at) VALUES('p1','m1','=FORMULA','SUCCEEDED','CARD',1000,20,100,'MWK',$1,$1),('p2','m2','OTHER','SUCCEEDED','CARD',9999,999,0,'MWK',$1,$1)`,[start]);});
  it('returns tenant and currency isolated integer summaries',async()=>{const response=await app.inject({url:`/v1/reports/summary?reportType=TRANSACTION_ACTIVITY&currency=MWK&periodStart=${encodeURIComponent(start)}&periodEnd=${encodeURIComponent(end)}`,headers:session('one-token')});expect(response.statusCode,response.body).toBe(200);expect(response.json()).toMatchObject({merchantId:'m1',currency:'MWK',grossPaymentMinor:'1000',refundedMinor:'100',feeMinor:'20',netMerchantMinor:'880',environment:'sandbox'});});
  it('creates one durable immutable export for identical concurrent and retry requests',async()=>{const responses=await Promise.all([app.inject(post('one-token','same-export',payload)),app.inject(post('one-token','same-export',payload))]);expect(responses.every(x=>x.statusCode===201),responses.map(x=>x.body).join('\n')).toBe(true);expect(new Set(responses.map(x=>x.json().id)).size).toBe(1);const id=responses[0].json().id;expect(Number((await db.query('SELECT count(*) FROM report_exports WHERE merchant_id=$1',[`m1`])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE resource_id=$1 AND action='REPORT_EXPORT_REQUESTED'`,[id])).rows[0].count)).toBe(1);expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE resource_id=$1 AND action='REPORT_EXPORT_COMPLETED'`,[id])).rows[0].count)).toBe(1);await expect(db.query(`UPDATE report_exports SET row_count=9 WHERE id=$1`,[id])).rejects.toThrow(/immutable/i);});
  it('rejects changed idempotency payload and hides detail and downloads cross merchant',async()=>{const created=await app.inject(post('one-token','conflict-key',payload));expect(created.statusCode,created.body).toBe(201);expect((await app.inject(post('one-token','conflict-key',{...payload,reportType:'PLATFORM_FEES'}))).statusCode).toBe(409);const id=created.json().id;expect((await app.inject({url:`/v1/report-exports/${id}`,headers:session('two-token')})).statusCode).toBe(404);expect((await app.inject({url:`/v1/report-exports/${id}/download`,headers:session('two-token')})).statusCode).toBe(404);});
  it('downloads deterministic safe CSV, records each download, isolates lists and enforces permissions',async()=>{const created=await app.inject(post('one-token','download-key',payload)),id=created.json().id,response=await app.inject({url:`/v1/report-exports/${id}/download`,headers:session('one-token')});expect(response.statusCode,response.body).toBe(200);expect(response.headers['content-disposition']).toMatch(/^attachment; filename="transaction_activity-rpt_[a-f0-9]+\.csv"$/);expect(response.body).toContain("'=FORMULA");expect((await app.inject({url:'/v1/report-exports',headers:session('two-token')})).json().total).toBe(0);expect(Number((await db.query(`SELECT count(*) FROM audit_events WHERE action='REPORT_DOWNLOADED' AND resource_id=$1`,[id])).rows[0].count)).toBe(1);expect((await app.inject({url:'/v1/audit-events',headers:session('two-token')})).json().total).toBe(0);expect((await app.inject({url:'/v1/report-exports',headers:session('viewer-token')})).statusCode).toBe(403);});
});
