import { describe,expect,it,vi } from 'vitest';
import { buildApp } from '../src/app.js';
import { loadConfig } from '../src/config.js';
import { MemoryRateLimitStore } from '../src/rateLimit.js';
import type { Db } from '../src/db.js';

const base={DATABASE_URL:'postgres://localhost/giantpay_test',PASSWORD_PEPPER:'p'.repeat(32),COOKIE_SECRET:'c'.repeat(32),FRONTEND_ORIGIN:'http://127.0.0.1:5173',PAYMENT_PROVIDER:'sandbox',SANDBOX_WEBHOOK_SECRET:'w'.repeat(32)};
const db={query:vi.fn().mockResolvedValue({rows:[],rowCount:1})} as unknown as Db;

describe('security hardening',()=>{
  it('uses atomic-style counters and expires windows without timers',async()=>{let now=0;const store=new MemoryRateLimitStore(()=>now);expect((await store.consume('a',2,10)).allowed).toBe(true);expect((await store.consume('a',2,10)).allowed).toBe(true);expect(await store.consume('a',2,10)).toMatchObject({allowed:false,remaining:0});now=10_001;expect((await store.consume('a',2,10)).allowed).toBe(true);});
  it('returns the normalized 429 body and headers',async()=>{const config=loadConfig({...base,NODE_ENV:'test',RATE_LIMIT_GENERAL_MAX:'1'});const app=await buildApp(config,db);await app.inject('/missing');const response=await app.inject('/missing');expect(response.statusCode).toBe(429);expect(response.json().error.code).toBe('RATE_LIMITED');expect(response.headers['retry-after']).toBeDefined();expect(response.headers['ratelimit-limit']).toBe('1');await app.close();});
  it('does not let untrusted forwarding headers choose the client identity',async()=>{const config=loadConfig({...base,NODE_ENV:'test',RATE_LIMIT_GENERAL_MAX:'1'});const app=await buildApp(config,db);expect((await app.inject({url:'/missing',headers:{'x-forwarded-for':'198.51.100.1'}})).statusCode).toBe(404);expect((await app.inject({url:'/missing',headers:{'x-forwarded-for':'203.0.113.2'}})).statusCode).toBe(429);await app.close();});
  it('honors forwarding only when the immediate proxy is explicitly trusted',async()=>{const config=loadConfig({...base,NODE_ENV:'test',TRUSTED_PROXIES:'127.0.0.1',RATE_LIMIT_GENERAL_MAX:'1'});const app=await buildApp(config,db);expect((await app.inject({url:'/missing',headers:{'x-forwarded-for':'198.51.100.1'}})).statusCode).toBe(404);expect((await app.inject({url:'/missing',headers:{'x-forwarded-for':'203.0.113.2'}})).statusCode).toBe(404);await app.close();});
  it('rejects missing CSRF and accepts matching tokens for cookie mutations',async()=>{const app=await buildApp(loadConfig({...base,NODE_ENV:'test'}),db);const denied=await app.inject({method:'POST',url:'/v1/auth/logout',headers:{cookie:'giantpay_session=x',origin:base.FRONTEND_ORIGIN}});expect(denied.statusCode).toBe(403);expect(denied.json().error.code).toBe('CSRF_REJECTED');const allowed=await app.inject({method:'POST',url:'/v1/auth/logout',headers:{cookie:'giantpay_session=x; giantpay_csrf=y',origin:base.FRONTEND_ORIGIN,'x-csrf-token':'y'}});expect(allowed.statusCode).toBe(204);await app.close();});
  it('sets API security headers and rejects unsupported content types',async()=>{const app=await buildApp(loadConfig({...base,NODE_ENV:'test'}),db);const response=await app.inject('/v1/health/live');expect(response.headers['x-content-type-options']).toBe('nosniff');expect(response.headers['content-security-policy']).toContain("default-src 'none'");expect(response.headers['x-powered-by']).toBeUndefined();expect((await app.inject({method:'POST',url:'/v1/auth/register',headers:{'content-type':'text/plain'},payload:'no'})).statusCode).toBe(415);await app.close();});
  it('rejects production without secure distributed configuration',()=>{const secureDatabase='postgres://database.invalid/giantpay?sslmode=verify-full';expect(()=>loadConfig({...base,DATABASE_URL:secureDatabase,NODE_ENV:'production',WEBHOOK_SECRET_KEY:'k'.repeat(32)})).toThrow(/REDIS_URL/);expect(()=>loadConfig({...base,DATABASE_URL:secureDatabase,NODE_ENV:'production',WEBHOOK_SECRET_KEY:'k'.repeat(32),REDIS_URL:'redis:\/\/cache',TRUSTED_PROXIES:'10.0.0.1'})).toThrow(/TLS/);});
});
