/* eslint-disable @typescript-eslint/no-explicit-any -- action callbacks are narrowed by the discriminated mutation union at their call sites. */
import { useState } from 'react';
import { Alert } from '@/components/feedback/Alert';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Checkbox } from '@/components/ui/Checkbox';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import { ApiError } from '@/services/api/errors';
import type { AddressKind, EvidenceCategory, EvidenceOwnerType, OnboardingDraft, QuestionnaireAnswers } from '@/types/onboarding';
import { useOnboardingAction, useSubmitOnboarding } from './useOnboardingQueries';

const inputClass = 'h-10 w-full rounded-[var(--radius-sm)] border border-[var(--color-neutral-300)] bg-white px-3 text-sm focus:border-[var(--color-blue-500)]';
const labelClass = 'flex flex-col gap-1 text-sm font-medium text-[var(--color-neutral-700)]';
const value = (form: FormData, name: string) => String(form.get(name) ?? '').trim();
const numeric = (form: FormData, name: string) => Number(value(form, name));
const checked = (form: FormData, name: string) => form.get(name) === 'on';

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-4">{children}</CardContent></Card>; }
function ErrorAlert({ error }: { error: unknown }) { return error ? <Alert variant="danger">{error instanceof ApiError ? error.message : 'The request could not be completed.'}</Alert> : null; }

export function GranularOnboardingForm({ draft, onCancelInformation }: { draft: OnboardingDraft; onCancelInformation: () => void }) {
  const action = useOnboardingAction();
  const submit = useSubmitOnboarding();
  const [submitKey] = useState(() => crypto.randomUUID());
  const [section, setSection] = useState(draft.currentStep);
  const [responseText, setResponseText] = useState<Record<string, string>>({});
  const [declared, setDeclared] = useState(Boolean(draft.questionnaire?.declarationAccepted));
  const busy = action.isPending || submit.isPending;
  const run = async (operation: Parameters<typeof action.mutateAsync>[0]) => { action.reset(); await action.mutateAsync(operation); };
  const ownership = draft.beneficialOwners.reduce((sum, owner) => sum + owner.ownershipBasisPoints, 0);
  const hasAddresses = new Set(draft.addresses.map(address => address.kind)).size === 2;
  const ready = Boolean(draft.business.legalName && hasAddresses && draft.directors.length && draft.beneficialOwners.length && ownership === 10000 && draft.representatives.length && draft.questionnaire?.declarationAccepted && draft.evidenceMetadata.length);

  return <div className="space-y-5">
    <nav aria-label="Onboarding sections" className="flex flex-wrap gap-2">
      {['Business and addresses', 'People', 'Questionnaire', 'Evidence metadata', 'Review'].map((name, index) => <Button key={name} type="button" size="sm" variant={section === index + 1 ? 'primary' : 'secondary'} onClick={() => setSection(index + 1)}>{index + 1}. {name}</Button>)}
    </nav>
    <ErrorAlert error={action.error ?? submit.error} />

    {draft.status === 'INFORMATION_REQUIRED' && <Section title="Requested information">
      <Alert variant="warning">Respond to every open request, update the relevant sections, then resubmit for internal sandbox review.</Alert>
      {draft.informationRequests.length === 0 && <Alert variant="danger">The backend did not return the information request details. Resubmission cannot be completed safely.</Alert>}
      {draft.informationRequests.map(request => <div key={request.id} className="rounded-lg border border-[var(--color-neutral-200)] p-4">
        <p className="font-semibold">{request.reason}</p><p className="text-sm text-[var(--color-neutral-500)]">Evidence reference: {request.evidenceReference}</p>
        {request.respondedAt ? <Alert variant="success">Response submitted.</Alert> : <><label className={labelClass}>Response<textarea className={`${inputClass} min-h-28 py-2`} value={responseText[request.id] ?? ''} onChange={event => setResponseText(old => ({ ...old, [request.id]: event.target.value }))} minLength={10} maxLength={4000} /></label><Button type="button" disabled={busy || (responseText[request.id]?.trim().length ?? 0) < 10} onClick={() => void run({ type: 'information-response', requestId: request.id, response: responseText[request.id].trim() })}>Send response</Button></>}
      </div>)}
      <div className="flex gap-2"><Button type="button" variant="secondary" onClick={onCancelInformation}>Back to status</Button><Button type="button" disabled={busy || !draft.informationRequests.length || draft.informationRequests.some(request => !request.respondedAt)} onClick={() => void run({ type: 'resubmit' })}>Resubmit application</Button></div>
    </Section>}

    {section === 1 && <>
      <Section title="Business profile"><form className="grid gap-4 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void run({ type: 'business', value: { legalName: value(f,'legalName'), tradingName: value(f,'tradingName') || undefined, registrationNumber: value(f,'registrationNumber') || undefined, taxId: value(f,'taxId') || undefined, businessType: value(f,'businessType'), industry: value(f,'industry'), incorporationCountry: value(f,'incorporationCountry').toUpperCase(), operatingCountry: value(f,'operatingCountry').toUpperCase(), contactEmail: value(f,'contactEmail'), contactPhone: value(f,'contactPhone'), website: value(f,'website') || undefined, expectedMonthlyVolumeMin: numeric(f,'expectedMonthlyVolumeMin'), expectedMonthlyVolumeMax: numeric(f,'expectedMonthlyVolumeMax'), expectedMonthlyValueMin: numeric(f,'expectedMonthlyValueMin'), expectedMonthlyValueMax: numeric(f,'expectedMonthlyValueMax'), intendedChannels: f.getAll('intendedChannels') as Array<'CARD'|'MOBILE_MONEY'|'BANK_TRANSFER'>, settlementAccountReference: value(f,'settlementAccountReference') || undefined } }); }}>
        {[['legalName','Legal name'],['tradingName','Trading name'],['registrationNumber','Registration number (leave blank to keep saved value)'],['taxId','Tax identifier (leave blank to keep saved value)'],['businessType','Business type'],['industry','Industry'],['incorporationCountry','Incorporation country'],['operatingCountry','Operating country'],['contactEmail','Contact email'],['contactPhone','Contact phone'],['website','Website'],['settlementAccountReference','Settlement account reference (leave blank to keep saved value)']].map(([name,label]) => <label key={name} className={labelClass}>{label}<Input name={name} defaultValue={name === 'registrationNumber' || name === 'taxId' || name === 'settlementAccountReference' ? '' : String(draft.business[name as keyof typeof draft.business] ?? '')} required={['legalName','businessType','industry','incorporationCountry','operatingCountry','contactEmail','contactPhone'].includes(name)} type={name.includes('Email') || name === 'contactEmail' ? 'email' : name === 'website' ? 'url' : 'text'} /></label>)}
        {[['expectedMonthlyVolumeMin','Minimum monthly transactions'],['expectedMonthlyVolumeMax','Maximum monthly transactions'],['expectedMonthlyValueMin','Minimum monthly value (minor units)'],['expectedMonthlyValueMax','Maximum monthly value (minor units)']].map(([name,label]) => <label key={name} className={labelClass}>{label}<Input name={name} type="number" min="0" required defaultValue={String(draft.business[name as keyof typeof draft.business] ?? 0)} /></label>)}
        <fieldset className="sm:col-span-2"><legend className="text-sm font-medium">Intended channels</legend><div className="flex flex-wrap gap-4">{(['CARD','MOBILE_MONEY','BANK_TRANSFER'] as const).map(channel => <label key={channel} className="flex items-center gap-2 text-sm"><input type="checkbox" name="intendedChannels" value={channel} defaultChecked={draft.business.intendedChannels?.includes(channel)} />{channel.replaceAll('_',' ')}</label>)}</div></fieldset>
        <Button className="sm:col-span-2 sm:justify-self-end" type="submit" loading={action.isPending}>Save business profile</Button>
      </form></Section>
      <Section title="Registered and operating addresses"><div className="space-y-2">{draft.addresses.map(address => <div key={address.id} className="flex justify-between rounded border p-3"><span><strong>{address.kind}</strong> — {address.line1}, {address.city}, {address.country}</span><Button size="sm" variant="ghost" onClick={() => void run({ type:'remove-address', id:address.id })}>Remove</Button></div>)}</div>
        <form className="grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const f=new FormData(event.currentTarget); void run({ type:'add-address', value:{ kind:value(f,'kind') as AddressKind, line1:value(f,'line1'), line2:value(f,'line2'), city:value(f,'city'), region:value(f,'region'), postalCode:value(f,'postalCode'), country:value(f,'country').toUpperCase() } }); event.currentTarget.reset(); }}><label className={labelClass}>Kind<select className={inputClass} name="kind"><option value="REGISTERED">Registered</option><option value="OPERATING">Operating</option></select></label>{[['line1','Address line 1'],['line2','Address line 2'],['city','City'],['region','Region'],['postalCode','Postal code'],['country','Country code']].map(([n,l])=><label key={n} className={labelClass}>{l}<Input name={n} required={['line1','city','country'].includes(n)} defaultValue={n==='country'?'MW':''}/></label>)}<Button type="submit">Add address</Button></form>
      </Section></>}

    {section === 2 && <PeopleSection draft={draft} busy={busy} run={run} />}
    {section === 3 && <QuestionnaireSection draft={draft} declared={declared} setDeclared={setDeclared} run={run} />}
    {section === 4 && <EvidenceSection draft={draft} run={run} />}
    {section === 5 && <Section title="Review and submit"><ul className="list-disc space-y-1 pl-5 text-sm"><li>Business profile: {draft.business.legalName ? 'saved' : 'missing'}</li><li>Registered and operating addresses: {hasAddresses ? 'complete' : 'both required'}</li><li>Directors: {draft.directors.length}</li><li>Beneficial ownership: {ownership / 100}% (must equal 100%)</li><li>Authorized representatives: {draft.representatives.length}</li><li>Questionnaire version 2026-01: {draft.questionnaire?.declarationAccepted ? 'complete' : 'incomplete'}</li><li>Active evidence metadata records: {draft.evidenceMetadata.length}</li></ul>{!ready && <Alert variant="warning">Complete every required section before submission. Metadata-only evidence satisfies the current sandbox validator when it references an already stored object; GiantPay does not upload or verify that object.</Alert>}<Button disabled={!ready || busy} loading={submit.isPending} onClick={event => { const button=event.currentTarget; if(button.dataset.submitting)return; button.dataset.submitting='true'; void submit.mutateAsync(submitKey).finally(()=>delete button.dataset.submitting); }}>Submit for sandbox review</Button></Section>}
  </div>;
}

function PeopleSection({ draft, busy, run }: { draft: OnboardingDraft; busy: boolean; run: (action: Parameters<ReturnType<typeof useOnboardingAction>['mutateAsync']>[0]) => Promise<void> }) {
  const personForm = (kind:'add-director'|'add-owner'|'add-representative') => (event:React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const f=new FormData(event.currentTarget); const base={ fullName:value(f,'fullName'), email:value(f,'email'), nationality:value(f,'nationality').toUpperCase(), identificationNumber:value(f,'identificationNumber') }; const operation = kind==='add-owner' ? {type:kind,value:{...base,ownershipBasisPoints:numeric(f,'ownershipBasisPoints')}} as const : kind==='add-representative' ? {type:kind,value:{fullName:base.fullName,email:base.email,telephone:value(f,'telephone'),authority:value(f,'authority'),identificationNumber:base.identificationNumber}} as const : {type:kind,value:base} as const; void run(operation); event.currentTarget.reset(); };
  return <Section title="Directors, beneficial owners, and representatives">
    {[['Directors',draft.directors,'remove-director'],['Beneficial owners',draft.beneficialOwners,'remove-owner'],['Authorized representatives',draft.representatives,'remove-representative']] .map(([title,items,remove]) => <div key={String(title)}><h3 className="font-semibold">{String(title)}</h3>{(items as Array<{id:string;fullName:string}>).map(item=><div key={item.id} className="flex justify-between border-b py-2 text-sm"><span>{item.fullName}</span><Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run({type:remove as 'remove-director',id:item.id})}>Remove</Button></div>)}</div>)}
    <form className="grid gap-3 sm:grid-cols-2" onSubmit={personForm('add-director')}><h3 className="sm:col-span-2 font-semibold">Add director</h3><PersonFields /><Button type="submit">Add director</Button></form>
    <form className="grid gap-3 sm:grid-cols-2" onSubmit={personForm('add-owner')}><h3 className="sm:col-span-2 font-semibold">Add beneficial owner</h3><PersonFields /><label className={labelClass}>Ownership basis points (10000 = 100%)<Input name="ownershipBasisPoints" type="number" min="1" max="10000" required /></label><Button type="submit">Add owner</Button></form>
    <form className="grid gap-3 sm:grid-cols-2" onSubmit={personForm('add-representative')}><h3 className="sm:col-span-2 font-semibold">Add authorized representative</h3>{[['fullName','Full name'],['email','Email'],['telephone','Telephone'],['authority','Authority'],['identificationNumber','Identification number (optional)']].map(([n,l])=><label key={n} className={labelClass}>{l}<Input name={n} type={n==='email'?'email':'text'} required={n!=='identificationNumber'} /></label>)}<Button type="submit">Add representative</Button></form>
  </Section>;
}
function PersonFields(){return <>{[['fullName','Full name'],['email','Email (optional)'],['nationality','Nationality country code'],['identificationNumber','Identification number (optional)']].map(([n,l])=><label key={n} className={labelClass}>{l}<Input name={n} type={n==='email'?'email':'text'} required={n==='fullName'||n==='nationality'} defaultValue={n==='nationality'?'MW':''}/></label>)}</>}

function QuestionnaireSection({draft,declared,setDeclared,run}:{draft:OnboardingDraft;declared:boolean;setDeclared:(v:boolean)=>void;run:(action:any)=>Promise<void>}) { const a=draft.questionnaire?.answers; return <Section title="Compliance questionnaire (version 2026-01)"><form className="space-y-4" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);const answers:QuestionnaireAnswers={natureOfBusiness:value(f,'natureOfBusiness'),sourceOfFunds:value(f,'sourceOfFunds'),expectedPaymentActivity:value(f,'expectedPaymentActivity'),countriesOfOperation:value(f,'countriesOfOperation').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),politicallyExposedPerson:checked(f,'politicallyExposedPerson'),sanctionsDeclaration:checked(f,'sanctionsDeclaration'),highRiskBusiness:checked(f,'highRiskBusiness'),thirdPartyPaymentProcessing:checked(f,'thirdPartyPaymentProcessing'),refundAndDisputeExpectations:value(f,'refundAndDisputeExpectations')};void run({type:'questionnaire',value:{version:'2026-01',declarationAccepted:declared,answers}})}}>{[['natureOfBusiness','Nature of business'],['sourceOfFunds','Source of funds'],['expectedPaymentActivity','Expected payment activity'],['refundAndDisputeExpectations','Refund and dispute expectations']].map(([n,l])=><label key={n} className={labelClass}>{l}<Textarea name={n} minLength={10} maxLength={2000} required defaultValue={a?.[n as keyof QuestionnaireAnswers] as string ?? ''}/></label>)}<label className={labelClass}>Countries of operation (comma-separated ISO codes)<Input name="countriesOfOperation" required defaultValue={a?.countriesOfOperation.join(', ') ?? 'MW'} /></label>{[['politicallyExposedPerson','A director or owner is a politically exposed person'],['sanctionsDeclaration','A director or owner is subject to sanctions'],['highRiskBusiness','The business conducts high-risk activity'],['thirdPartyPaymentProcessing','The business processes payments for third parties']].map(([n,l])=><label key={n} className="flex items-center gap-2 text-sm"><input type="checkbox" name={n} defaultChecked={Boolean(a?.[n as keyof QuestionnaireAnswers])}/>{l}</label>)}<label className="flex items-start gap-2 text-sm"><Checkbox checked={declared} onCheckedChange={v=>setDeclared(v===true)}/>I confirm these answers are accurate and I am authorized to make this declaration.</label><Button type="submit" disabled={!declared}>Save questionnaire</Button></form></Section> }

function EvidenceSection({draft,run}:{draft:OnboardingDraft;run:(action:any)=>Promise<void>}) { return <Section title="Evidence metadata"><Alert variant="warning">File upload is unavailable. Register metadata only for a document already stored in an approved secure service. The opaque storage reference is encrypted by the backend and is never returned.</Alert>{draft.evidenceMetadata.map(e=><div key={e.id} className="flex justify-between border-b py-2 text-sm"><span>{e.category}: {e.fileName} ({e.mediaType}, {e.sizeBytes} bytes)</span><Button size="sm" variant="ghost" onClick={()=>void run({type:'remove-evidence',id:e.id})}>Remove</Button></div>)}<form className="grid gap-3 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);void run({type:'add-evidence',value:{category:value(f,'category') as EvidenceCategory,ownerType:value(f,'ownerType') as EvidenceOwnerType,ownerId:value(f,'ownerId')||undefined,storageReference:value(f,'storageReference'),mediaType:value(f,'mediaType') as 'application/pdf',sizeBytes:numeric(f,'sizeBytes'),sha256:value(f,'sha256').toLowerCase(),fileName:value(f,'fileName')}});event.currentTarget.reset();}}><label className={labelClass}>Category<select className={inputClass} name="category">{['BUSINESS_REGISTRATION','TAX_REGISTRATION','DIRECTOR_IDENTIFICATION','BENEFICIAL_OWNER_IDENTIFICATION','ADDRESS','BANK_ACCOUNT','ADDITIONAL_COMPLIANCE'].map(x=><option key={x}>{x}</option>)}</select></label><label className={labelClass}>Owner type<select className={inputClass} name="ownerType">{['MERCHANT','DIRECTOR','BENEFICIAL_OWNER','REPRESENTATIVE'].map(x=><option key={x}>{x}</option>)}</select></label>{[['ownerId','Owner record ID (optional)'],['storageReference','Approved opaque storage reference'],['fileName','Safe file name'],['sha256','SHA-256 (64 lowercase hex characters)'],['sizeBytes','Size in bytes']].map(([n,l])=><label key={n} className={labelClass}>{l}<Input name={n} type={n==='sizeBytes'?'number':'text'} required={!['ownerId'].includes(n)} /></label>)}<label className={labelClass}>Media type<select className={inputClass} name="mediaType"><option>application/pdf</option><option>image/jpeg</option><option>image/png</option></select></label><Button type="submit">Register metadata</Button></form></Section> }
